### ISSUE TITLE
Upgrade Pact Mock Service

### ISSUE THREAD

**Issue by matthewbalvanz-wf** [pact-foundation/pact-python#10]
The version of Mock Service used during the build of pact-python is currently out of date and does not include a recent change to make the pact specification version consistent across the various language implementations: https://github.com/pact-foundation/pact-mock_service/commit/5b89d95167013ac4b11030b362c439f5632e7540

We need to upgrade to at least 2.1.0 to ensure pact-python is creating compatible pact files.

**Comment by jslvtr** [comment]
🚢 Looks good to me! Also my apologies for being unavailable, hope to have a bit more time in the coming weeks.

**Comment by matthewbalvanz-wf** [comment]
No worries @jslvtr. I myself have been busy with things outside the project and haven't made as much contributions as I like.

**Comment by matthewbalvanz-wf** [comment]
Resolved with #11
