### ISSUE TITLE
what is the plan to support messaging API?

### ISSUE THREAD

**Issue by singlaive** [pact-foundation/pact-python#101]
pact Java and a few other clients support messaging style of API already. Any road map for Python?

**Comment by hernan0216** [comment]
i think that this issue is [duplicated](https://github.com/pact-foundation/pact-python/issues/88).

**Comment by singlaive** [comment]
No news yet. Anyway, I will do it myself.

**Comment by YOU54F** [comment]
Implemented as part of https://github.com/pact-foundation/pact-python/pull/119

We are looking for more contributors and help in bringing pact v3 and v4 features via the pact-rust core, so please this issue for more detail

https://github.com/pact-foundation/pact-python/issues/312
