### ISSUE TITLE
Dynamic args to setup() is incompatible with PyCharm

### ISSUE THREAD

**Issue by antonagestam** [pact-foundation/pact-python#111]
PyCharm complains that `Package containing module 'pact' is not listed in project requirements` when importing the pacts module. I'm guessing this is due to `setup()` being called with an expanded dict that PyCharm isn't looking at. Is there any specific reason for this, or can it be changed to a call with kwargs instead?

https://github.com/pact-foundation/pact-python/blob/master/setup.py#L121

**Comment by elliottmurray** [comment]
Like so?
https://github.com/pact-foundation/pact-python/pull/124
