### ISSUE TITLE
Please update pact-provider-verifier options to support fetching pacts automatically from a Pact Broker

### ISSUE THREAD

**Issue by bethesque** [pact-foundation/pact-python#114]
A user may specify `--broker-base-url`, `--provider` and one or more `--consumer-version-tag` flags, and the provider-verifier will automatically fetch the right pacts for the provider. When called this way, no pact URL argument is required (though it can be specified at the same time if you so wanted).

On publishing the verification results, one or more `--provider-version-tag` can be supplied.

The full CLI docs can be found here: https://github.com/pact-foundation/pact-ruby-standalone/releases#pact-provider-verifier

Support for this method of calling the verifier will be required for the upcoming "pending pacts" feature, where pacts that have not yet been successfully verified before will be able to be run without failing the provider build.

**Comment by elliottmurray** [comment]
Hopefully this is nearly done - https://github.com/pact-foundation/pact-python/pull/120

**Comment by elliottmurray** [comment]
Close this now?

**Comment by bethesque** [comment]
Closing!
