### ISSUE TITLE
No clear instructions on setting up development environment for pact-python

### ISSUE THREAD

**Issue by dhoomakethu** [pact-foundation/pact-python#12]
Clear instructions on setting up development environment is missing in the README.md
Multiple preconditions required to use pact-python .
on OSX, I had to

- Install ruby --> specifically v2.2.2
- Install bundler, rake and any other ruby related dependencies
- ~~use ./scripts/build to build mock service (which again failed complaining `Gem::InstallError: rack requires Ruby version >= 2.2.2.
An error occurred while installing rack (2.0.3), and Bundler cannot continue.
Make sure that `gem install rack -v '2.0.3'` succeeds before bundling.`~~
- spend hours finding a way to make the build script work ~~(with no success)~~

-----update----
~~I was able to build the mockservice binary successfully, but running it resulted in the following error`/Users/sanjay/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- pact/mock_service/cli (LoadError)
	from /Users/sanjay/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from ./pact-mock-service:2:in `<main>'`~~

-----update2----
Finally I got the build working, all I did was 

1. install ruby v2.2.2 with rvm
2. install bundler 
3. ran `make package`

The key was earlier I was using v2.4.0 but the make package command ended with 
`You can only 'bundle install' using Ruby 2.2, because that's what Traveling Ruby uses.`

I am updating here, so that any new user (read ruby noob)  trying pact-python and getting lost :P

**Comment by ftobia** [comment]
+1
I ran into the same issues. These instructions worked for me on OSX.

**Comment by matthewbalvanz-wf** [comment]
Sorry about that @dhoomakethu and @ftobia, looks like I missed updating the development section when I started moving it from the Docker version of Pact to the Ruby one. I'll get that added to the README for future readers.
