### ISSUE TITLE
Running tests as part of previous test results in pact_mock_service error {"error_code": "unauthorized"}

### ISSUE THREAD

**Issue by xjurcak** [pact-foundation/pact-python#122]
Hi i use example from pact python for consumer tests and place it alongside with my tests in project. I start test using command  `python -m unittest discover -v tests`, but test which use pact fails with stack:
`Failure
Traceback (most recent call last):
  File "C:\Users\jurca\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Users\jurca\AppData\Local\Programs\Python\Python37\lib\unittest\case.py", line 628, in run
    testMethod()
  File "C:\Users\jurca\mofa\surglogs\exports\src\tests\test_controllers\test_test.py", line 32, in test_get_user
    result = user('UserA')
  File "C:\Users\jurca\mofa\surglogs\exports\venv\lib\site-packages\pact\pact.py", line 312, in __exit__
    self.verify()
  File "C:\Users\jurca\mofa\surglogs\exports\venv\lib\site-packages\pact\pact.py", line 213, in verify
    assert resp.status_code == 200, resp.text
AssertionError: {"error_code": "unauthorized"}`

Test example:
```
import atexit
import unittest

import requests
from pact import Consumer, Provider

def user(user_name):
    """Fetch a user object by user_name from the server."""
    uri = 'http://localhost:1234/users/' + user_name
    return requests.get(uri).json()

pact = Consumer('Consumer').has_pact_with(Provider('Provider'))
pact.start_service()
atexit.register(pact.stop_service)


class GetUserInfoContract(unittest.TestCase):
  def test_get_user(self):
    expected = {
      'username': 'UserA',
      'id': 123,
      'groups': ['Editors']
    }

    (pact
     .given('UserA exists and is not an administrator')
     .upon_receiving('a request for UserA')
     .with_request('get', '/users/UserA')
     .will_respond_with(200, body=expected))

    with pact:
      result = user('UserA')

    self.assertEqual(result, expected)


if __name__ == '__main__':
    unittest.main()
```

If i run test individualy everything works just fine. I try running this example on windows and in docker using python:3.6 image

I am using pact-python 0.20.0

**Comment by elliottmurray** [comment]
Just checking nothing running on that port? You could try to run it on a different port and specify it with the provider? Doesn't explain while it works stand alone

**Comment by xjurcak** [comment]
I already figure it out. Another old test mock request.get method and dont properly tearDown to reset mock to previous states. So i think we could close this issue as irrelevant.
