### ISSUE TITLE
Why version 0.20.0 is not in master?

### ISSUE THREAD

**Issue by copalco** [pact-foundation/pact-python#123]

**Comment by matthewbalvanz-wf** [comment]
@mefellows Is it possible when you tagged 0.20.0 that the commit wasn't pushed to master?

**Comment by mefellows** [comment]
hmmm maybe, possibly... I can't actually even see that tag locally (or this commit `ef89d7`). I might need to dig in a bit

**Comment by m-aciek** [comment]
I suppose the ticket can be closed now.

**Comment by bethesque** [comment]
We couldn't work this out! Though I did identify that `git push origin --tags` (in the release notes) did not seem to push to master. I've changed it to `git push origin master --tags`.

I've pulled the commits back into master (though they're a bit messy). 🤷‍♀ We'll probably never know what happened!
