### ISSUE TITLE
pact-python failing to install intermittently on Jenkins

### ISSUE THREAD

**Issue by mayanknaileshpatel** [pact-foundation/pact-python#125]
I have a python project wherein I am specifying pact-python as a dependency and building it on our Jenkins pipeline. The package is fetched from our organization's artifactory instance (which in turn gets the packages from here: https://files.pythonhosted.org/packages)

The package installation fails randomly (sometimes it does pass with the same code) with below stack trace:

[91m    ERROR: Command errored out with exit status 1:
 command: /app/env/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-2uidl1mw/pact-python/setup.py'"'"'; __file__='"'"'/tmp/pip-install-2uidl1mw/pact-python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-bwvfr5jk/install-record.txt --single-version-externally-managed --compile --install-headers /app/env/include/site/python3.6/pact-python
     cwd: /tmp/pip-install-2uidl1mw/pact-python/
Complete output (50 lines):
running install
running build
running build_py
creating build
creating build/lib
creating build/lib/pact
copying pact/consumer.py -> build/lib/pact
copying pact/verify.py -> build/lib/pact
copying pact/provider.py -> build/lib/pact
copying pact/constants.py -> build/lib/pact
copying pact/__version__.py -> build/lib/pact
copying pact/pact.py -> build/lib/pact
copying pact/matchers.py -> build/lib/pact
copying pact/__init__.py -> build/lib/pact
running install_lib
creating /app/env/lib/python3.6/site-packages/pact
copying build/lib/pact/consumer.py -> /app/env/lib/python3.6/site-packages/pact
copying build/lib/pact/verify.py -> /app/env/lib/python3.6/site-packages/pact
copying build/lib/pact/provider.py -> /app/env/lib/python3.6/site-packages/pact
copying build/lib/pact/constants.py -> /app/env/lib/python3.6/site-packages/pact
copying build/lib/pact/__version__.py -> /app/env/lib/python3.6/site-packages/pact
copying build/lib/pact/pact.py -> /app/env/lib/python3.6/site-packages/pact
copying build/lib/pact/matchers.py -> /app/env/lib/python3.6/site-packages/pact
copying build/lib/pact/__init__.py -> /app/env/lib/python3.6/site-packages/pact
byte-compiling /app/env/lib/python3.6/site-packages/pact/consumer.py to consumer.cpython-36.pyc
byte-compiling /app/env/lib/python3.6/site-packages/pact/verify.py to verify.cpython-36.pyc
byte-compiling /app/env/lib/python3.6/site-packages/pact/provider.py to provider.cpython-36.pyc
byte-compiling /app/env/lib/python3.6/site-packages/pact/constants.py to constants.cpython-36.pyc
byte-compiling /app/env/lib/python3.6/site-packages/pact/__version__.py to __version__.cpython-36.pyc
byte-compiling /app/env/lib/python3.6/site-packages/pact/pact.py to pact.cpython-36.pyc
byte-compiling /app/env/lib/python3.6/site-packages/pact/matchers.py to matchers.cpython-36.pyc
byte-compiling /app/env/lib/python3.6/site-packages/pact/__init__.py to __init__.cpython-36.pyc
running install_egg_info
running egg_info
writing pact_python.egg-info/PKG-INFO
writing dependency_links to pact_python.egg-info/dependency_links.txt
writing entry points to pact_python.egg-info/entry_points.txt
writing requirements to pact_python.egg-info/requires.txt
writing top-level names to pact_python.egg-info/top_level.txt
reading manifest file 'pact_python.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'pact/test'
no previously-included directories found matching 'pact/bin'
no previously-included directories found matching 'e2e'
writing manifest file 'pact_python.egg-info/SOURCES.txt'
Copying pact_python.egg-info to /app/env/lib/python3.6/site-packages/pact_python-0.19.0-py3.6.egg-info
running install_scripts
Installing pact-verifier script to /app/env/bin
writing list of installed files to '/tmp/pip-record-bwvfr5jk/install-record.txt'
error: <urlopen error [Errno 111] Connection refused>
[0m[91mERROR: Command errored out with exit status 1: /app/env/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-2uidl1mw/pact-python/setup.py'"'"'; __file__='"'"'/tmp/pip-install-2uidl1mw/pact-python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-bwvfr5jk/install-record.txt --single-version-externally-managed --compile --install-headers /app/env/include/site/python3.6/pact-python Check the logs for full command output.

I have tried to fix the pact-python versions to 0.19.0 ans 0.20.0 but it does not solve the issue.
What is the url that the installation is failing to communicate with ?

**Comment by bethesque** [comment]
Most likely it's the github release URL for the internal pact-ruby-standalone package that it delegates to. Something like `https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v1.78.0/pact-1.78.0-linux-x86.tar.gz`

**Comment by mayanknaileshpatel** [comment]
Thanks, it seems to be some kind of networking issue. Closing this.
