### ISSUE TITLE
specifying tag provider version when publishing verification results

### ISSUE THREAD

**Issue by moritztk** [pact-foundation/pact-python#126]
Hi!
How can I tag the provider version when publishing verification results?
I would like to do this, so I can see in the matrix which versions are in fact production versions.

**Comment by bethesque** [comment]
There's a PR in play for this here: https://github.com/pact-foundation/pact-python/pull/120

It should be released soon.

**Comment by bethesque** [comment]
If you don't want to wait for that, you can use the pact broker client https://github.com/pact-foundation/pact_broker-client#create-version-tag It has a docker image, and a standalone executable. Or, you can just do a PUT with curl to `/pacticipant/PACTICIPANT/versions/VERSION/tags/TAG`. You have to set the Content-Type to 'application/json' to do this.

**Comment by elliottmurray** [comment]
Close this now?

**Comment by bethesque** [comment]
Closing! Released in 0.21.0
