### ISSUE TITLE
Multiple custom-provider-header

### ISSUE THREAD

**Issue by ChengLiPP** [pact-foundation/pact-python#133]
Hi pact team, 

I raised a bug in the pact-provider-verifier repo and Beth very kindly reviewed my issue and redirected me here, the problem is the custom-provider-header flag does not accept multiple entries.
https://github.com/pact-foundation/pact-provider-verifier/issues/55

Beth has added a test to show it does work in the base ruby code so the problem is from the python wrapper, which I believe is here.
https://github.com/pact-foundation/pact-python/blob/master/pact/verify.py#L79
https://click.palletsprojects.com/en/7.x/options/#multiple-options

Many thanks in advance 🙏

**Comment by elliottmurray** [comment]
#134 wrote some unit tests to validate but haven't verified the multiple headers. There is an e2e for one header so shouldn't break anything.

**Comment by ChengLiPP** [comment]
@elliottmurray Thank you for looking into this, really appreciated 👍

**Comment by elliottmurray** [comment]
#134 resolved this
