### ISSUE TITLE
Could not install pact-python using pip

### ISSUE THREAD

**Issue by fayeezahmed** [pact-foundation/pact-python#15]
Python version: 3.6.0
OS: Windows 10

Description:
When I try to install python using `pip install pact-python` as per the instructions. I get the following error message:
```
Could not find a version that satisfies the requirement pact-python (from versions: )
No matching distribution found for pact-python
```

I'm not sure if others are seeing this.

On another note.. it looks like this is in beta, any ideas on the full release? Is it 3-6 months away? or more?

**Comment by matthewbalvanz-wf** [comment]
Thanks @fayeezahmed, I haven't gotten the package uploaded to pypi.python.org yet, though I did spend some time this weekend sorting out theTravis CI -> pypi.python.org path this weekend. I hope to get that work completed soon.

On the beta front: #14 is the last major piece of work to meet what I think is the "1.0.0" mark for the project. There are some minor tweaks that could make it a little easier to use, but they are likely not required to reach the major version. I'm hoping to have that wrapped up in the next couple of weeks.

**Comment by matthewbalvanz-wf** [comment]
@fayeezahmed I pushed up v0.4.0 to pypi.python.org today. Would you be able to try the install again and let me know if you encounter anything unusual?

**Comment by matthewbalvanz-wf** [comment]
@fayeezahmed Closing this issue for now as it should be resolved. If you are still encountering issues please feel free to reopen this issue.
