### ISSUE TITLE
Support OpenAPI document validator for requests

### ISSUE THREAD

**Issue by francbartoli** [pact-foundation/pact-python#158]
Any plan to support the OpenAPI spec like this repo https://bitbucket.org/atlassian/swagger-request-validator/src/master/swagger-request-validator-pact/?

**Comment by mefellows** [comment]
What is the actual ask here? We have discussed how we support OAS better but what is it that you want pact to be able to do? We are currently discussing next  features in the RFC at https://github.com/pact-foundation/pact-specification/issues/71 perhaps you could articulate further there.

Also see our docs, there are some points about OAS you should be aware of first.

**Comment by francbartoli** [comment]
@mefellows I've read this before https://docs.pact.io/faq/convinceme#but-i-use-swaggeropenapi which suggests using the above plugin from Atlassian and lead me to ask if there was a similar attempt (or plan to have) in python. Is there anything else in the docs that I missed?

**Comment by mefellows** [comment]
Not that I'm aware of, but perhaps it's worth discussing in the RFC how better Swagger support could be integrated? I, along with other colleagues, have been [thinking about it](https://pactflow.io/blog/the-curious-case-for-the-provider-driven-contract/).

As an aside, https://bitbucket.org/atlassian/swagger-mock-validator/src/master/ may be useful for you and should work with your Pact setup right now.

**Comment by YOU54F** [comment]
This doesn't feel like it should be a feature of pact-python exclusively, it should either be a separate package, or considered as part of the pact-ecosystem.

Just to the time stamps, I am closing this and would request that it be raised on https://pact.canny.io/search?search=swagger if its still a feature you or the community are after - I've added a search anchor to previous discussions about swagger there
