### ISSUE TITLE
Support pending pacts

### ISSUE THREAD

**Issue by thatguysimon** [pact-foundation/pact-python#164]
Hi,
Please add support for the new "pending pacts" feature:
https://pact.canny.io/feature-requests/p/pending-pacts-prevent-consumers-being-able-to-break-provider-builds-with-changed

I might be able to open a PR for this myself if I get some guidance.

**Comment by bethesque** [comment]
I thought it was actually supported already, since @elliottmurray upgraded to the latest version of the ruby standalone, but I can't see any mention of the word "pending" in the codebase. I think it might just be a matter of exposing the right flags to the underlying CLI.

**Comment by bethesque** [comment]
The instructions are under the section "For implementations that wrap the ruby standalone" in https://github.com/pact-foundation/pact_broker/issues/320

**Comment by mefellows** [comment]
I had a quick look the other day Beth. It should be relatively straightforward - copy pasta of the approach to other flags
