### ISSUE TITLE
Can someone remove the manual upload from test_user_consumer.py

### ISSUE THREAD

**Issue by bethesque** [pact-foundation/pact-python#175]
https://github.com/pact-foundation/pact-python/blob/master/examples/e2e/tests/consumer/test_user_consumer.py

People keep copying it and having issues.

**Comment by elliottmurray** [comment]
Fixed in #177 which is actually the second time I've fixed it but this time I actually remembered to merge it....

**Comment by bethesque** [comment]
Thanks!
