### ISSUE TITLE
verify_wrapper.py has a bug related to headers

### ISSUE THREAD

**Issue by adriangabrieloros** [pact-foundation/pact-python#176]
the verify wrapper expects the 'custom_provider_headers' field: 

headers = kwargs.get('custom_provider_headers', [])

but from the verify.py the following is sent: 
 'custom_provider_header': list(headers),

So it expects headers, not header. 
I removed the extra 's' locally, and it works.

**Comment by elliottmurray** [comment]
Can I just check you actually mean verifier.py not cli/verify.py?

I think you're correct and it's a bug where I changed it in one place (the verifier class was the new addition so makes sense to fix it there)

**Comment by adriangabrieloros** [comment]
Yes, i confirm that.

**Comment by elliottmurray** [comment]
#178
