### ISSUE TITLE
Please create a RELEASING.md file

### ISSUE THREAD

**Issue by bethesque** [pact-foundation/pact-python#18]
It should have information on how to update the pact library dependencies and make a new release.

I've added pact python to the Pact Dependency Graph of Doom! Can you confirm that this is correct? https://github.com/pact-foundation/README/blob/master/dependency_graph.md

**Comment by matthewbalvanz-wf** [comment]
@bethesque The graph looks correct to me. Current master builds its own version of mock service and provider verifier, but with those projects publishing a standalone version I'd like to switch to downloading those from Github. I opened #20 to make that change.
