### ISSUE TITLE
when verify post request from mock server to provider, post data is None always.

### ISSUE THREAD

**Issue by himrlawrrence** [pact-foundation/pact-python#185]
the contract file is correct, like this.

{
  “method”: “post”,
  “path”: “/data”,
  “body”: {
    “username”: “UserA”
  }
}
but when i try to verify the provider. the api said post.data is None (which is expect “username: UserA”)

File “/xxxx/workspace/downstream/src/downstream.py”, line 32, in get_data
    name = data.get(‘username’)
AttributeError: ‘NoneType’ object has no attribute ‘get’

**Comment by mefellows** [comment]
Resolved - missing `content-type` header
