### ISSUE TITLE
Unable to import MessageConsumer from pact

### ISSUE THREAD

**Issue by olivzz** [pact-foundation/pact-python#199]
I could not import the MessageConsumer from pact otherwise able to import others. This also means that the example in https://github.com/pact-foundation/pact-python/blob/master/examples/message/tests/consumer/test_message_consumer.py  is not working as it should. Can someone let me know if this a bug or am I doing it wrongly?

![image](https://user-images.githubusercontent.com/78036394/105870092-97530900-6000-11eb-9e80-4736228e883a.png)

**Comment by elliottmurray** [comment]
I haven't released yet! I know William and co are doing another PR. If I get a chance I'll publish one though as it's still valuable

**Comment by ptsiakos77** [comment]
@olivzz You can install it from source if you want just to try things until a release is made using

 **_pip3.9 install -e git+https://github.com/pact-foundation/pact-python.git#egg=pact-python_**

**Comment by olivzz** [comment]
@elliottmurray Is there any alternative to Messageconsumer in the current release?
Also Do you know when will the new release happen?

**Comment by olivzz** [comment]
@elliottmurray  I see a new release. thanks. will let know if I face any issues with that before closing this issue.

**Comment by olivzz** [comment]
resolved
