### ISSUE TITLE
Reduce the download size for users by splitting the compiled application into a separate package for each platform

### ISSUE THREAD

**Issue by matthewbalvanz-wf** [pact-foundation/pact-python#20]
The current install package for pact-python is more than 60MBs and includes the mock service and provider verifier for platforms the user is not using. We should remove the requirement that the user download those unneeded versions.

**Comment by mefellows** [comment]
Maybe there is some work we can do to combine the Ruby projects into a single Gem/binary/dependency - I imagine most of the cost over the over head is the duplicate Ruby runtimes, and duplicate Gems (of which there must be a large amount of overlap).

Doing this would simplify the deployment of Python, JS and Golang.

**Comment by matthewbalvanz-wf** [comment]
> I imagine most of the cost over head is the duplicate Ruby runtimes

I think the traveling Ruby might be the majority of the size currently, and with mock service and provider verifier each having their own you end up with 2. I didn't have enough Ruby experience to get too much farther into deciding how they might be combined though.

With the ways things are setup today, I think I can bring the install size down to 15MBs, which removes 75% of today's install size.

**Comment by bethesque** [comment]
Yes, they could easily be bundled together. Let's do it.

**Comment by bethesque** [comment]
I've created a repo for it here: https://github.com/pact-foundation/pact-ruby-standalone

(putting it in an existing repo would cause strange recursive dependency problems with the gems)

**Comment by bethesque** [comment]
https://github.com/pact-foundation/pact-ruby-standalone/releases/tag/v0.0.1 Go nuts

**Comment by matthewbalvanz-wf** [comment]
This is awesome, thanks @bethesque!

**Comment by mefellows** [comment]
You're a machine!
