### ISSUE TITLE
SSL: DH_KEY_TOO_SMALL when running with generated cert

### ISSUE THREAD

**Issue by jurriaanpro** [pact-foundation/pact-python#220]
I've got this test for which I need the mock service to have ssl enabled. The flag `ssl=True` is set and I see that when running the test a cert gets created on the fly. However when the tests makes calls to this mock service an `SSL: DH_KEY_TOO_SMALL` error occurs.

A snippet of how the test looks like:
```python
class TestContract(unittest.TestCase):
    pact = None

    @classmethod
    def setUpClass(cls) -> None:
        cls.pact = Consumer("a-consumer").has_pact_with(
            Provider("a-provider"), host_name="0.0.0.0", port=8432, ssl=True
        )
        cls.pact.start_service()

    @classmethod
    def tearDownClass(cls) -> None:
        cls.pact.stop_service()

    def test_something(self):
        with self.pact:
            a_client = SomeClient("https://localhost:8432")
            a_client.get("/some-endpoint")
```

The error:
```
WARNING  urllib3.connectionpool:connectionpool.py:780 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1125)'))': /
```

The container that these tests run in (which is based on `python:3.8-slim`) has the following set in `/etc/ssl/openssl.cnf` which is most likely the reason for this.
```
[system_default_sect]
MinProtocol = TLSv1.2
CipherString = DEFAULT@SECLEVEL=2
```

I could probably work around it by making sure this becomes `CipherString = DEFAULT@SECLEVEL=1`, but I was wondering if the generated cert could be 'improved'?

**Comment by mefellows** [comment]
May I ask, why do you actually need the service to have TLS enabled? It's rare that it's a useful thing to do for a contract test, so just want to make sure we understand the use case.

**Comment by jurriaanpro** [comment]
The client uses `requests-oauthlib` to call endpoints which requires secure transport.

**Comment by mefellows** [comment]
ah, what a pain. Makes sense though.

**Comment by jurriaanpro** [comment]
In the meanwhile I've been able to work around it in multiple ways. One is editing `/etc/ssl/openssl.cnf` during build (which runs in a Docker container so it doesn't matter too much).

Used the following snippet for that:
```
sed 's/CipherString = DEFAULT@SECLEVEL=2/CipherString = DEFAULT@SECLEVEL=1/' /etc/ssl/openssl.cnf > /etc/ssl/openssl.cnf.new
mv /etc/ssl/openssl.cnf.new /etc/ssl/openssl.cnf
```

But as that's kinda hacky, I've chosen to refactor the client to allow passing of a `session` param, so during these tests we can pass it a simple `requests.Session` and in prod we let it initialize the `requests_oauthlib.OAuth2Session`.

I'll close the issue, but it might still be interesting to look into 'improving' the generated cert.
