### ISSUE TITLE
Publishing verifier through CLI

### ISSUE THREAD

**Issue by olivzz** [pact-foundation/pact-python#221]
Hi, I am using pact-python 1.3.4. Does pact-verify has the capability to stop from publishing or by default "publish-verification-results" seems to be false but still it is publishing to the broker. Moreover I am not able to set any values to the parameter as seen below I get error.
Error: --publish-verification-results option does not take a value

**Comment by elliottmurray** [comment]
If you put a provider version number in it will by default try to publish. I did this thinking that people would want to do both all times? I can change it and add that flag if necessary. I think you might be able to override with the env var (something like PUBLISH_VERIFICATION_RESULTS=false)

**Comment by olivzz** [comment]
I guess you mean provider_app_version. If so, can provider_app_version be left as optional? I tried but the test failed so I think it is a manadatory param.

**Comment by elliottmurray** [comment]
#222 if you want to check it out and test it. It seems to be correct behaviour now. I'll create a release probably at the weekend

**Comment by elliottmurray** [comment]
Released with 1.3.6
