### ISSUE TITLE
Not able to publish to broker when using broker token

### ISSUE THREAD

**Issue by asivasankari** [pact-foundation/pact-python#236]
pactdef = pact.Consumer('nectarConnectLambda').has_pact_with(pact.Provider('nectarHash'),
        publish_to_broker=True,
        broker_base_url=os.environ['PACT_FLOW_URL'],
        broker_token=os.environ['PACT_FLOW_AUTH_TOKEN'],
        specification_version='3.0.0')

When tests are executed getting below error message, even though broker_username is not defined.

PactBroker command: ['/home/circleci/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pact/bin/pact/bin/pact-broker', 'publish', '--consumer-app-version=0.0.0', '--broker-base-url=*************************************************', '--broker-token=**********************', '/home/circleci/code/application/nectarconnectlambda-nectarhash.json']
You cannot provide both a username/password and a bearer token. If your Pact Broker uses a bearer token, please remove the username and password configuration.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/circleci/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pact/pact.py", line 241, in stop_service
    pact_dir=self.pact_dir
  File "/home/circleci/.pyenv/versions/3.7.10/lib/python3.7/site-packages/pact/broker.py", line 95, in publish
    f"There was an error while publishing to the pact broker at {url}.")
RuntimeError: There was an error while publishing to the pact broker at *************************************************.

We are moving to new pact broker where we only have the option of using broker token.

**Comment by elliottmurray** [comment]
So I'm not using Pactflow so can't comment on that bit but the token should work the same - can you check that PR #226 didn't fix that? Version 1.3.7 from pypi

**Comment by asivasankari** [comment]
Getting same error with version 13.7 also

**Comment by mefellows** [comment]
Just a guess and worth ruling out, but what environment variables do you have exported? If `PACT_BROKER_USERNAME` or `PACT_BROKER_PASSWORD` are set, they may be detected and hence the error may occur.

**Comment by asivasankari** [comment]
Looks like yes PACT_BROKER_USERNAME=user and PACT_BROKER_PASSWORD=pwd are getting set to default value. Below is my config in circleci. I am using python image with required libraries installed. Setting only below two environment variables. 

            export PACT_FLOW_URL=${PACT_FLOW_URL}
            export PACT_BROKER_TOKEN=${PACT_BROKER_TOKEN}
            unset PACT_BROKER_USERNAME
            unset PACT_BROKER_PASSWORD
            nosetests --with-coverage  --cover-package=src --cover-xml --exe --all-modules --cover-inclusive

I have to manually unset the above two -PACT_BROKER_USERNAME & PACT_BROKER_PASSWORD . After this its working
