### ISSUE TITLE
Support bytes as response type

### ISSUE THREAD

**Issue by stefanello8** [pact-foundation/pact-python#241]
I have a Consumer that expects bytes as response. Something like this:
`.will_respond_with(200, body=bytes([0x13, 0x00, 0x00, 0x00, 0x08, 0x00]))`

But it seems like bytes are not supported as response type of an interaction, since I'm getting a value error from pact (_ValueError: Unknown type: <class 'bytes'>_).

Is it possible to support bytes as well or is there any workaround for this kind of scenario?

**Comment by joshua-badger** [comment]
I also have a situation this would be helpful for. I'd love to see this happen.

**Comment by joshua-badger** [comment]
This issue has not actually been solved yet, the fix applied was naive in a few assumptions.
