### ISSUE TITLE
API should allow multiple requests to be stubbed at the same time

### ISSUE THREAD

**Issue by bethesque** [pact-foundation/pact-python#25]
Multiple interactions should be allowed to be set up at the same time. The /delete call should be called before the test, not before each interaction is set up. 

See this example using bash here: https://gist.github.com/bethesque/9d81f21d6f77650811f4

https://github.com/pact-foundation/pact-python/blob/master/pact/pact.py#L119

```python
def setup(self):
        """Configure the Mock Service to ready it for a test."""
        try:
            payload = {
                'description': self._description,
                'provider_state': self._provider_state,
                'request': self._request,
                'response': self._response
            }

            resp = requests.delete(
                self.uri + '/interactions', headers=self.HEADERS)

            assert resp.status_code == 200, resp.content
            resp = requests.post(
                self.uri + '/interactions',
                headers=self.HEADERS, json=payload)

            assert resp.status_code == 200, resp.content
        except AssertionError:
            raise
```

**Comment by AnObfuscator** [comment]
Since this blocks something I'm working on, I'm willing to fix it myself and offer a PR, if I know the approach the Python team wants to use.

I suspect the delete is in the setup method so that it can be elegantly handled by the Python with statement context manager. If so, the delete method would have to remain in the setup method and the Pact class will have to be modified to manage multiple payloads. It would be a little tricky to do without breaking the current API, if that's a concern; but it's doable.

**Comment by bethesque** [comment]
You can use a PUT with `{"interactions": [...]}`to add multiple requests at the same time. This will effectively do the DELETE and multiple POSTs. The Python API would need to be modified to allow multiple requests to be set up at once. Don't know if you can do this with python, but you can chain requests like this in Ruby:

```python
(pact
     .given('Authenticated')
     .upon_receiving('a request to /login')
     .with_request('get', '/login/UserA')
     .will_respond_with(200, body=expected))
     .given('UserA exists and is not an administrator')
     .upon_receiving('a request for UserA')
     .with_request('get', '/users/UserA')
     .will_respond_with(200, body=expected)
```

**Comment by AnObfuscator** [comment]
Yeah, you can certainly chain like that in Python, and that's what I was thinking it should look like. 

The Pact class would just need to store lists of payloads instead of only one payload at a time. I've given it some thought, and I'll give it a shot.

**Comment by bethesque** [comment]
The only catch is that it needs something to tell it when to trigger the PUT. The ruby one does a POST to the mock service every time it receives a `will_respond_with` method call, because it's already called the DELETE in a before-test hook from the test framework. If you use a PUT and method chaining, as above, I can't see how it would know when to do the PUT. But I'm sure you'll work out something!

**Comment by matthewbalvanz-wf** [comment]
When I had previously thought about how to do this in Python I had been expecting to go down the `addInteraction` route that the JS and Go implementations did. This function chaining would work as well though.

> I suspect the delete is in the setup method so that it can be elegantly handled by the Python with statement context manager.

You are correct. I was thinking we could pull `_request` and `_response` off the `Pact` class and replace with an `interactions` list that contains a object with those two values. `will_responsd_with` would then create a new "interaction" and add it to the list. At that point we might just need to adjust the [setup](https://github.com/pact-foundation/pact-python/blob/master/pact/pact.py#L109-L129) to perform the delete and multiple POST/PUT calls to setup all of the interactions the user defined?

**Comment by AnObfuscator** [comment]
@matthewbalvanz-wf That's approximately the approach I was thinking. It's actually fairly straightforward. I implemented a first crack at it last night, but I'm having more trouble getting the nosetests to run than I am understanding how to modify the Pact class. :(

**Comment by AnObfuscator** [comment]
@matthewbalvanz-wf  https://github.com/pact-foundation/pact-python/pull/26
