### ISSUE TITLE
Asynchronous message provider testing possible?

### ISSUE THREAD

**Issue by emilvelidjanov01** [pact-foundation/pact-python#275]
Official pact documentation says asynchronous message testing is not featured yet here: https://docs.pact.io/roadmap/feature_support
However, the example under examples/message suggests otherwise?

Is the documentation not up-to-date? Or is the example wrongly named/documented?

**Comment by elliottmurray** [comment]
That probably should be a Y. You should be able to follow the examples and get this working. Always open to some good contribution examples btw!

**Comment by mefellows** [comment]
I've just updated that table to reflect the current status. I think some more docs on the pact-python home page to show this would be great, but you can look at the examples for now. 

Thanks for reporting @emilvelidjanov01 .
