### ISSUE TITLE
Pact-Python verifier requires a set_up_provider_state and tear_down_provider_state to be provided

### ISSUE THREAD

**Issue by fndg87** [pact-foundation/pact-python#28]
For each response verification to be run against a provider, the pact-verifier program tries to find the set_up_provider_state and the tear_down_provider_state.

` pact-verifier --provider-base-url=http://localhost:8081 --pact-urls=./consumer_api_contract.json
`
> 
> 
>      Got 0 failures and 2 other errors:
> 
>      1.1) Failure/Error: set_up_provider_state interaction.provider_state, options[:consumer]
>           
>           RuntimeError:
>             Could not find provider state "Administrator user" for consumer platform_ui
> 
>      1.2) Failure/Error: tear_down_provider_state interaction.provider_state, options[:consumer]
>           
>           RuntimeError:
>             Could not find provider state "Administrator user" for consumer platform_ui
> 
> 

Pact-Python Verifier version:

/Library/Python/2.7/site-packages/pact/bin/verifier/lib/vendor/ruby/2.2.0/gems/pact-1.11.1/lib/pact/provider/

**Comment by bethesque** [comment]
@fndg87 which version of pact-python are you using? The path you provided only shows the ruby gem version. I suspect that this might be resolved if you update to the most recent release of pact python.

**Comment by fndg87** [comment]
Hi @bethesque , my apologies. I'm having pact-python==0.5.0

**Comment by bethesque** [comment]
I can't work out if 0.6.0 has been released or not. It's showing in the releases page, but it's not tagged as the latest. @matthewbalvanz-wf what's the status of the integration with the new standalone packages, and which version is/will it be in?

**Comment by matthewbalvanz-wf** [comment]
Thanks @fndg87, I'll do a little digging to see what might be happening here.

@bethesque It seems I should code late at night less often, as I failed to complete a couple of steps when I cut 0.6.0. That version is not current, using pact-ruby-standalone 1.0.0.

**Comment by matthewbalvanz-wf** [comment]
I setup a branch where the end to end tests are configured to not use the provider state setup:
https://github.com/pact-foundation/pact-python/compare/stateless-contracts?expand=1

and it does appear to be a difference between 0.5.0 and 0.6.0. With 0.5.0 I see the same issue you encountered @fndg87, but upgrading to 0.6.0 I get a passing result with a message from the Ruby app that it skipped the provider state setup:

```
$ make e2e
bash -c "$E2E"
[2017-06-26 19:50:23] INFO  WEBrick 1.3.1
[2017-06-26 19:50:23] INFO  ruby 2.2.2 (2015-04-13) [x86_64-darwin13]
[2017-06-26 19:50:23] INFO  WEBrick::HTTPServer#start: pid=92673 port=1234
.
----------------------------------------------------------------------
Ran 1 test in 0.080s

OK

Writing pact for provider to ./pacts/consumer-provider.json
[2017-06-26 19:50:30] INFO  going to shutdown ...
[2017-06-26 19:50:30] INFO  WEBrick::HTTPServer#start done.
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
Connection to localhost port 5000 [tcp/commplex-main] succeeded!
Reading pact at ./pacts/consumer-provider.json

Verifying a pact between consumer and provider
  Given a stateless service exists
    a request for a resource
      with GET /resources/1
        returns a response which
WARN: Skipping set up for provider state 'a stateless service exists' for consumer 'consumer' as there is no --provider-states-setup-url specified.
127.0.0.1 - - [26/Jun/2017 19:50:31] "GET /resources/1 HTTP/1.1" 200 -
          has status code 200
          has a matching body

1 interaction, 0 failures


Tearing down Flask server
```
@fndg87 Would you be able to try upgrading to 0.6.0 and let me know if that resolves the issue you encountered?

**Comment by fndg87** [comment]
Hi @bethesque  and @matthewbalvanz-wf , after upgrading to the 0.6.0 version I'm no longer seeing this issue:

```
Reading pact at ./consumer_app-provider_api.json

Verifying a pact between consumer_app and provider_api
  Given An administrator user
    an authentication request
      with POST /identity/auth/authenticate/
        returns a response which
WARN: Skipping set up for provider state 'An administrator user' for consumer 'consumer_app' as there is no --provider-states-setup-url specified.
          has status code 200
          has a matching body

1 interaction, 0 failures
```

Thanks for addressing this so quick.

**Comment by fndg87** [comment]
Hi @bethesque  and @matthewbalvanz-wf , after upgrading to the 0.6.0 version I'm no longer seeing this issue:

```
Reading pact at ./consumer_app-provider_api.json

Verifying a pact between consumer_app and provider_api
  Given An administrator user
    an authentication request
      with POST /identity/auth/authenticate/
        returns a response which
WARN: Skipping set up for provider state 'An administrator user' for consumer 'consumer_app' as there is no --provider-states-setup-url specified.
          has status code 200
          has a matching body

1 interaction, 0 failures
```

Thanks for addressing this so quick.

**Comment by bethesque** [comment]
👍
