### ISSUE TITLE
Pact-Python verifier fails to verify against remote broker

### ISSUE THREAD

**Issue by fndg87** [pact-foundation/pact-python#29]
> pact-verifier --provider-base-url=http://localhost:8081 --pact-broker-username MyBasicAuthUser123 --pact-broker-password MyBasicAuthPassword123 --pact-urls https://myremotebroker.pact.dius.com.au/

`shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
/Library/Python/2.7/site-packages/pact/bin/verifier/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler/shared_helpers.rb:53:in `chdir': No such file or directory - getcwd (Errno::ENOENT)
	from /Library/Python/2.7/site-packages/pact/bin/verifier/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler/shared_helpers.rb:53:in `block in chdir'
	from /Library/Python/2.7/site-packages/pact/bin/verifier/lib/ruby/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
	from /Library/Python/2.7/site-packages/pact/bin/verifier/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler/shared_helpers.rb:52:in `chdir'
	from /Library/Python/2.7/site-packages/pact/bin/verifier/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler.rb:363:in `load_gemspec_uncached'
	from /Library/Python/2.7/site-packages/pact/bin/verifier/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler.rb:353:in `load_gemspec'
	from /Library/Python/2.7/site-packages/pact/bin/verifier/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler/dsl.rb:53:in `gemspec'
	from /Library/Python/2.7/site-packages/pact/bin/verifier/lib/vendor/Gemfile:3:in `eval_gemfile'
	from /Library/Python/2.7/site-packages/pact/bin/verifier/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler/dsl.rb:32:in `instance_eval'
	from /Library/Python/2.7/site-packages/pact/bin/verifier/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler/dsl.rb:32:in `eval_gemfile'
	from /Library/Python/2.7/site-packages/pact/bin/verifier/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler/dsl.rb:10:in `evaluate'
	from /Library/Python/2.7/site-packages/pact/bin/verifier/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler/definition.rb:25:in `build'
	from /Library/Python/2.7/site-packages/pact/bin/verifier/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler.rb:155:in `definition'
	from /Library/Python/2.7/site-packages/pact/bin/verifier/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler.rb:118:in `setup'
	from /Library/Python/2.7/site-packages/pact/bin/verifier/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler/setup.rb:8:in `<top (required)>'
	from /Library/Python/2.7/site-packages/pact/bin/verifier/lib/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
	from /Library/Python/2.7/site-packages/pact/bin/verifier/lib/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /Library/Python/2.7/site-packages/pact/bin/verifier/lib/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'`

**Comment by fndg87** [comment]
Pact python version is :

pact-python==0.5.0

**Comment by bethesque** [comment]
Sorry, I think the pact python people will have to help you with this one. From the stack trace, it doesn't look like a problem with the underlying ruby implementation (which is what I work on)

**Comment by matthewbalvanz-wf** [comment]
@fndg87 I haven't had any luck yet reproducing this issue. I have opened a PR to fix another issue with the broker user/password arguments being wrong (#24). Once we get that released would you be willing to try this scenario again and see if you get a different result?

**Comment by matthewbalvanz-wf** [comment]
@fndg87 I just released v0.6.2 which includes #24 to fix the username/password options. Would you be able to try your example above again and let me know the results?

**Comment by fndg87** [comment]
I pip installed pact-python==0.6.2 and now I'm seeing a new error:
`
/Library/Python/2.7/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.1.0/lib/pact/consumer_contract/service_consumer.rb:9:in `initialize': undefined method `[]' for nil:NilClass (NoMethodError)
	from /Library/Python/2.7/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.1.0/lib/pact/consumer_contract/service_consumer.rb:25:in `new'
	from /Library/Python/2.7/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.1.0/lib/pact/consumer_contract/service_consumer.rb:25:in `from_hash'
	from /Library/Python/2.7/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.1.0/lib/pact/consumer_contract/consumer_contract.rb:35:in `from_hash'
	from /Library/Python/2.7/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-support-1.1.0/lib/pact/consumer_contract/consumer_contract.rb:43:in `from_json'
	from /Library/Python/2.7/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-1.14.0/lib/pact/provider/rspec.rb:25:in `honour_pactfile'
	from /Library/Python/2.7/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-1.14.0/lib/pact/provider/pact_spec_runner.rb:129:in `block in initialize_specs'
	from /Library/Python/2.7/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-1.14.0/lib/pact/provider/pact_spec_runner.rb:125:in `each'
	from /Library/Python/2.7/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-1.14.0/lib/pact/provider/pact_spec_runner.rb:125:in `initialize_specs'
	from /Library/Python/2.7/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-1.14.0/lib/pact/provider/pact_spec_runner.rb:34:in `run'
	from /Library/Python/2.7/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-1.14.0/lib/pact/cli/run_pact_verification.rb:60:in `run_with_pact_uri'
	from /Library/Python/2.7/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-1.14.0/lib/pact/cli/run_pact_verification.rb:48:in `run_specs'
	from /Library/Python/2.7/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-1.14.0/lib/pact/cli/run_pact_verification.rb:22:in `call'
	from /Library/Python/2.7/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-1.14.0/lib/pact/cli/run_pact_verification.rb:14:in `call'
	from /Library/Python/2.7/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.1.3/lib/pact/provider_verifier/app.rb:66:in `block in verify_pacts'
	from /Library/Python/2.7/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.1.3/lib/pact/provider_verifier/app.rb:57:in `collect'
	from /Library/Python/2.7/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.1.3/lib/pact/provider_verifier/app.rb:57:in `verify_pacts'
	from /Library/Python/2.7/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/pact-provider-verifier-1.1.3/lib/pact/provider_verifier/cli.rb:21:in `verify'
	from /Library/Python/2.7/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /Library/Python/2.7/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Python/2.7/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /Library/Python/2.7/site-packages/pact/bin/pact/lib/vendor/ruby/2.2.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /Library/Python/2.7/site-packages/pact/bin/pact/lib/app/pact-provider-verifier.rb:2:in `<main>'

`

**Comment by bethesque** [comment]
From the stacktrace, it looks like the json document doesn't have a "consumer" key. Is there an error response being returned perhaps? Can you test the call using curl?

**Comment by elliottmurray** [comment]
old issue
