### ISSUE TITLE
_wait_for_server_stop cannot stop process and throw AssertionError

### ISSUE THREAD

**Issue by sentyaev** [pact-foundation/pact-python#294]
There is a docker-compose configuration with django application.
When inside docker I run `pytest` command to execute `pact` tests is fails on `_wait_for_server_stop` call. Looks like that process cannot be stopped for some reason.

The problem is that it's happening only for the first time when I build containers. All the following execution of `pytest` completes successfully.

I'm trying to figre out the reason, but without success.

This is a stacktrace:
```
__________ TestProvider.test_something __________

self = <pact.message_provider.MessageProvider object at 0x7fc61e720430>

    def _wait_for_server_stop(self):
        """Wait for server to finish, or raise exception after timeout."""
        retry = 20
        while True:
            self._process.terminate()
            time.sleep(0.1)
            try:
>               assert not self._process.is_alive()
E               AssertionError

/usr/local/lib/python3.10/site-packages/pact/message_provider.py:92: AssertionError

During handling of the above exception, another exception occurred:

    def test_something():
       provider = MessageProvider(
            message_providers={
                'something triggered': message_provider
            },
            provider='api',
            consumer='consumer',
            pact_dir='./_pacts',
        )

>       with provider:

application/tests/services/test_pact.py:100:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/usr/local/lib/python3.10/site-packages/pact/message_provider.py:156: in __exit__
    self._stop_proxy()
/usr/local/lib/python3.10/site-packages/pact/message_provider.py:108: in _stop_proxy
    self._wait_for_server_stop()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <pact.message_provider.MessageProvider object at 0x7fc61e720430>

    def _wait_for_server_stop(self):
        """Wait for server to finish, or raise exception after timeout."""
        retry = 20
        while True:
            self._process.terminate()
            time.sleep(0.1)
            try:
                assert not self._process.is_alive()
                return 0
            except AssertionError:
                if retry == 0:
>                   raise RuntimeError("Process timed out")
E                   RuntimeError: Process timed out

/usr/local/lib/python3.10/site-packages/pact/message_provider.py:96: RuntimeError
----------------------------- Captured stdout call -----------------------------
INFO: Reading pact at ./_pacts/api-consumer.json


Verifying a pact between api and consumer
  Given something triggered
    message-name
WARN: Skipping set up for provider state 'something triggered' for consumer 'consumer' as there is no --provider-states-setup-url specified.
      has matching content

1 interaction, 0 failures
=========================== short test summary info ============================
FAILED application/tests/services/test_pact.py::TestProvider::test_something
```

**Comment by sentyaev** [comment]
One thing I found.
If I change this line https://github.com/pact-foundation/pact-python/blob/master/pact/message_provider.py#L89
from `self._process.terminate()` to `self._process.kill()` everything works.

I guess it's something related to how `SIGTERM` and `SIGKILL` works inside docker container.

**Comment by duzumaki** [comment]
`kill()` uses `SIGKILL` which terminates the process immediately. 
`terminate()` uses `SIGTERM` which gracefully tries to kill the process, which means something can block it from it trying to kill the process.

My guess is there's child processes laying around which terminate can't kill but kill can't. 

They should probably add a python 3.7 check there. use kill if python 3.7 or above and terminate if below

**Comment by YOU54F** [comment]
Thanks for the pr @sentyaev 

Should we consider @duzumaki's comment regarding python 3.7.

Are we able to try on Python 3.6 and see if it works without the change request in the PR?

Many thanks!

**Comment by sentyaev** [comment]
@YOU54F sure, I'll try to find some time to test it.

**Comment by sentyaev** [comment]
FYI. I did more experiments with this issue and looks like it's an issue with particular test configuration. Now I'm investigating what is preventing `process.terminate()` to stop process.

**Comment by YOU54F** [comment]
Thank you so much @sentyaev, I really appreciate you taking the time and sharing your learnings
