### ISSUE TITLE
broker-broker_app-1：bundler: command not found: puma

### ISSUE THREAD

**Issue by allinone-1** [pact-foundation/pact-python#303]
centos_7_perf:/home/contract_test/pact-python-master/examples/broker #/usr/local/bin/docker-compose-linux up
[+] Running 2/0
 ⠿ Container broker-postgres-1    Created                                                                                                 0.0s
 ⠿ Container broker-broker_app-1  Created                                                                                                 0.0s
Attaching to broker-broker_app-1, broker-nginx-1, broker-postgres-1
broker-postgres-1    |
broker-postgres-1    | PostgreSQL Database directory appears to contain a database; Skipping initialization
broker-postgres-1    |
broker-postgres-1    | 2022-09-06 01:28:42.771 UTC [1] LOG:  starting PostgreSQL 14.5 (Debian 14.5-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
broker-postgres-1    | 2022-09-06 01:28:42.772 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
broker-postgres-1    | 2022-09-06 01:28:42.772 UTC [1] LOG:  listening on IPv6 address "::", port 5432
broker-postgres-1    | 2022-09-06 01:28:42.776 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
broker-postgres-1    | 2022-09-06 01:28:42.785 UTC [24] LOG:  database system was shut down at 2022-09-06 01:28:41 UTC
broker-postgres-1    | 2022-09-06 01:28:42.794 UTC [1] LOG:  database system is ready to accept connections
**broker-broker_app-1  | `/pact_broker` is not writable.
broker-broker_app-1  | Bundler will use `/tmp/bundler20220906-6-o8ia2z6' as your home directory temporarily.
broker-broker_app-1  | bundler: command not found: puma
broker-broker_app-1  | Install missing gem executables with `bundle install`
broker-broker_app-1 exited with code 127**

**Comment by mikegeeves** [comment]
This looks like [this issue](https://github.com/pact-foundation/pact-broker-docker/issues/62)
Is this somewhere "new" or could it be using previously pulled images? Have you tried pulling down the latest image / what version are you using? (of Docker, and of the broker)

e.g. here I have:
```
$ docker images|grep pact-broker
pactfoundation/pact-broker                                           2                 939fce733047   7 weeks ago     474MB
pactfoundation/pact-broker                                           2.102.2.0         939fce733047   7 weeks ago     474MB
pactfoundation/pact-broker                                           latest            939fce733047   7 weeks ago     474MB
```

```
$ docker --version
Docker version 20.10.14, build a224086
```

**Comment by allinone-1** [comment]
centos_7_perf:/home/contract_test/pact-python-master/examples/broker #docker images
REPOSITORY                             TAG                 IMAGE ID            CREATED             SIZE
docker.io/postgres                     latest              b37c2a6c1506        13 days ago         376 MB
docker.io/pactfoundation/pact-cli      latest              22467f0a66e8        2 weeks ago         94.9 MB
docker.io/nginx                        alpine              804f9cebfdc5        3 weeks ago         23.5 MB
docker.io/pactfoundation/pact-broker   latest              939fce733047        7 weeks ago         474 MB
centos_7_perf:/home/contract_test/pact-python-master/examples/broker #docker --version
Docker version 1.13.1, build 7d71120/1.13.1

**Comment by mikegeeves** [comment]
I'm not sure if a version of Docker that old is supported/expected to work - 1.13.1 is from 2017-02-08, and it looks like from the linked issue that support for the 2019-03 Docker version is soon to be removed due to issues going ahead.

Would an updated Docker version be problematic? I imagine it may be for a fairly old CentOS version?

Any additional suggestions @bethesque ? I would assume not given investigation and debugging the more recent 19.03 version seemed problematic enough!

**Comment by mefellows** [comment]
Yep, good spot Mike. I don't think the latest alpine images work on older versions of Docker. We need to be on the latest, or people (rightfully) complain about security vulnerabilities.

The Pactflow image uses a similar base image, and we require a minimum of Docker 20: https://docs.pactflow.io/docs/on-premises/system-requirements#docker-version.

**Comment by allinone-1** [comment]
> Yep, good spot Mike. I don't think the latest alpine images work on older versions of Docker. We need to be on the latest, or people (rightfully) complain about security vulnerabilities.
> 
> The Pactflow image uses a similar base image, and we require a minimum of Docker 20: https://docs.pactflow.io/docs/on-premises/system-requirements#docker-version.
-------------------------------------------------
Docker version 20.10.9, build c2ea9bc
d2d716b09038   nginx:alpine                 "/docker-entrypoint.…"   13 minutes ago   Up 13 minutes             80/tcp, 0.0.0.0:8443->443/tcp, :::8443->443/tcp   broker-nginx-1
7b63e0f23d78   pactfoundation/pact-broker   "sh ./entrypoint.sh …"   13 minutes ago   Up 13 minutes (healthy)   0.0.0.0:80->9292/tcp, :::80->9292/tcp             broker-broker_app-1
b8430d6a4e9e   postgres                     "docker-entrypoint.s…"   13 minutes ago   Up 13 minutes (healthy)   0.0.0.0:5432->5432/tcp, :::5432->5432/tcp         broker-postgres-1

After configuration, do I need a password to log in?   https://localhost  ，the user name and password i don't know

**Comment by mefellows** [comment]
https://github.com/pact-foundation/pact-python/blob/master/examples/broker/docker-compose.yml#L33-L34

**Comment by allinone-1** [comment]
> https://github.com/pact-foundation/pact-python/blob/master/examples/broker/docker-compose.yml#L33-L34

Thank you very much

**Comment by mefellows** [comment]
You're welcome! I'll close this off for now.
