### ISSUE TITLE
When I performed the contract test, I failed

### ISSUE THREAD

**Issue by allinone-1** [pact-foundation/pact-python#305]
Error log：
AssertionError: Actual interactions do not match expected interactions for mock MockService.
Missing requests:
	GET /info?name=test_0

pact-mock-service.log:
W, [2022-09-08T22:59:03.012442 #30988]  WARN -- : Verifying - actual interactions do not match expected interactions.

**Comment by YOU54F** [comment]
Could you provide a reproducible example of your test and code base.

Are you actually making that request, and configured your consumer client to use the Pact mock provider?

For bonus points on how to raise a good question / issue and some steps you can provide for additional context https://docs.pact.io/help/how_to_ask_for_help#4-ask-a-good-question 👍🏾

**Comment by allinone-1** [comment]
> 
**version:**
Docker version 20.10.9, build c2ea9bc
Docker Compose version v2.10.2
CentOS Linux release 7.7.1908 (Core)
Python 3.7.1
**code**
import atexit
import unittest
from pact import Consumer, Provider
import requests
import json

def user(user_name):
    """Fetch a user object by user_name from the server."""
    uri = 'http://localhost:8080/info'
    res = requests.get(uri, {"name": user_name}).json()
    return res
pact = Consumer('Consumer_a').has_pact_with(Provider('Provider_api'))
pact.start_service()
atexit.register(pact.stop_service)

class GetUserInfoContract(unittest.TestCase):
  def test_get_user(self):
    expected =     {
        "id":10000,
        "name":"test_0",
        "path":"chongqing",
        "others":{
            "email":"test_0@sangfor.com",
            "phone":"18000000000"
        }
    }
    expected = json.dumps(expected)
    print("expec"+expected)
    # headers = {}
    (pact
     .given('User exists and is test_0')
     .upon_receiving('a request for test_0')
     .with_request(
        method="GET",
        path="/info",
        query={"name":"test_0"}

     )
     .will_respond_with(200, body=expected))
    with pact:
      result = user('test_0')
    print(result)
    self.assertEqual(result, expected)
if __name__ =="__main__":
    unittest.main(verbosity=2)
------------------------------------------------------------
error log:
  File "D:\soft\python39\lib\site-packages\pact\pact.py", line 378, in __exit__
    self.verify()
  File "D:\soft\python39\lib\site-packages\pact\pact.py", line 277, in verify
    assert resp.status_code == 200, resp.text   # _------->   resp.status_code = 500_
AssertionError: Actual interactions do not match expected interactions for mock MockService.

Missing requests:
	GET /info?name=test_0

**Comment by mefellows** [comment]
Could you please try formatting with code gates a bit better?

> GET /info?name=test_0

This is pretty clear - your code is not sending that request to the mock server.

> res = requests.get(uri, {"name": user_name}).json()

Should that be `test_0` instead of `user_name`?

**Comment by allinone-1** [comment]
>
def user(user_name):
    """Fetch a user object by user_name from the server."""
    uri = 'http://localhost:8080/info'
    res = requests.get(uri, {"name": user_name}).json()
    return res
 ------------------
 with pact:
      result = user('test_0')   
# test_0 has been assigned to user_name

**Comment by YOU54F** [comment]
You need to configure the port of your pact mock provider to the port used in your code


taken from the readme


> The default hostname and port for the Pact mock service will be localhost:1234 but you can adjust this during Pact creation

you need to set the port to 8080, see the readme for an example 👍🏽

**Comment by YOU54F** [comment]
Or change the port to 1234 in the user function

**Comment by allinone-1** [comment]
> 
Thank you very much
