### ISSUE TITLE
Where does MessageProvider get messages from to validate?

### ISSUE THREAD

**Issue by elmanm** [pact-foundation/pact-python#310]
When I use the MessageProvider in a test, pact hits:
1. `localhost/ping`
2. `localhost/setup`: with a POST and body that is evaluated the message_provider handlers
3. `localhost/`: with a POST and body that is the contract

I can't seem to send messages to PACT to validate them. Should it be as a response in one of these? 
```python
def handler():
    return {"someId": "e2490de5-5bd3-43d5-b7c4-526e33f71304"}

@app.route("/ping"):
def ping():
    return "", 200

@app.route("/setup"):
def setup():
    return "", 201

@app.route("/")
def home():
    return {"someId": "e2490de5-5bd3-43d5-b7c4-526e33f71304"}

def test_verify_pact():
    message_providers = {"A State": handler}
    provider = MessageProvider(message_providers, "my-provider", "my-consumer")
    with provider:
        provider.verify()
```

When I run the test, I get something like this:
```
Actual: null
       Diff
       --------------------------------------
       Key: - is expected
            + is actual
       Matching keys and values are not shown
       -{
       -  "someId": "e2490de5-5bd3-43d5-b7c4-526e33f71304"
       -}
       Description of differences
       --------------------------------------
       * Expected a Hash but got nil at $
```
So I assume that I need to send the messages on to pact somewhere that I am not (because of the "nil").

**Comment by mefellows** [comment]
You need to map the scenarios (descriptions in the pact file) to message handlers. See https://github.com/pact-foundation/pact-python/blob/master/examples/message/tests/provider/test_message_provider.py#L41-L44 for an example.

Message Pact won't talk to HTTP endpoints as above - see https://docs.pact.io/getting_started/how_pact_works#non-http-testing-message-pact for the abstract on how we test non-HTTP endpoints.

**Comment by elmanm** [comment]
> You need to map the scenarios (descriptions in the pact file) to message handlers. See https://github.com/pact-foundation/pact-python/blob/master/examples/message/tests/provider/test_message_provider.py#L41-L44 for an example.

I have tried using description as the key instead of the state in my message_providers mapping as well, with the same result.
Stepping through the debugger I see that the message handlers are each called in the `_setup_states` of the provider, and the result is passed as a json request body to `/setup`. But that is it, the response from "/setup" isn't used anywhere.

> Message Pact won't talk to HTTP endpoints as above - see https://docs.pact.io/getting_started/how_pact_works#non-http-testing-message-pact for the abstract on how we test non-HTTP endpoints.
I don't understand what you mean? The pact hits the 3 endpoints I listed when I run my test, I have breakpoints there that are hit everytime.

**Comment by mefellows** [comment]
> But that is it, the response from "/setup" isn't used anywhere.

Yes - it's used as a signal to setup the state internally to the provider (think of it as a `before` test type hook), not to return values for the test.

> I don't understand what you mean? The pact hits the 3 endpoints I listed when I run my test, I have breakpoints there that are hit everytime.

Is it a message provider or an HTTP provider? This is not how Message Pact works 

> I have tried using description as the key instead of the state in my message_providers mapping as well, with the same result.

Can you please share that code so we can take a look?

**Comment by elmanm** [comment]
It's a message provider.

Where does pact get the published messages from? How do I forward the messages to pact rather than my messaging service?

**Comment by elmanm** [comment]
The flow is the message provider:
1. pings the service to check it's running
2. POST to setup with the message provider body to set up the provider, expects 201 response
3. for each part of the contract POST to home ("/")

The code looks like this:
```python
from uuid import uuid4

from flask import Flask
from pact import MessageProvider

app = Flask(__name__)
app.states = {}


@app.route("/", methods=["POST"])
def home():
    return {"someId": str(uuid4())}   # seemingly ignored


@app.route("/ping")
def ping():
    return "", 200


@app.route("/setup", methods=["POST"])
def setup_route():
    return "", 201


def handler():
    return {"someId": str(uuid4())}


def test_pact():
    msg_provider = {"An event": handler}
    provider = MessageProvider(provider='my-provider', consumer='my-consumer', message_providers=msg_provider, proxy_port='5000')
    with provider:
        provider.verify()


def main():
    app.run()
```

I run `main` in one terminal (running the app) and then run `test_pact` in another.

My pact looks like this:
```json
{
  "consumer": {
    "name": "my-consumer"
  },
  "messages": [
    {
      "_id": "aeac9217222ed587b8a63294152ba38537b192bc",
      "contents": {
        "someId": "e2490de5-5bd3-43d5-b7c4-526e33f71304"
      },
      "description": "An event",
      "generators": {
        "body": {
          "$.someId": {
            "type": "Uuid"
          }
        },
        "metadata": {
          "RequestId": {
            "type": "Uuid"
          }
        }
      },
      "matchingRules": {
        "body": {
          "$.someId": {
            "combine": "AND",
            "matchers": [
              {
                "match": "regex",
                "regex": "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"
              }
            ]
          }
        },
        "metadata": {
          "RequestId": {
            "combine": "AND",
            "matchers": [
              {
                "match": "regex",
                "regex": "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"
              }
            ]
          }
        }
      },
      "metaData": {
        "RequestId": "e2490de5-5bd3-43d5-b7c4-526e33f71304",
        "contentType": "application/json"
      },
      "providerStates": [
        {
          "name": "A State"
        }
      ]
    }
  ],
  "metadata": {
    "pactSpecification": {
      "version": "3.0.0"
    }
  },
  "provider": {
    "name": "my-provider"
  }
}
```

This is a test application obviously, which doesn't publish any messages, if I were to make the application actually send messages, I want to route them to pact instead of say an sns Topic, is that right? Or is that magically handled inside pact?

**Comment by mefellows** [comment]
> Where does pact get the published messages from? How do I forward the messages to pact rather than my messaging service?

Have you seen the example above? You need to separate your protocol (SNS, Kafka etc.) from the message generating logic. 

Note the `createEvent` method [here](https://github.com/pactflow/example-provider-js-sns/blob/master/src/product/product.pact.test.js#L34) is separated from the service class that communicates to SNS [here](https://github.com/pactflow/example-provider-js-sns/blob/master/src/product/product.event.service.js#L9-L12).

You map the descriptions to the event generating function, not the actual protocol.

That is - you don't actually publish to SNS (or whatever queue).

This all happens in process within the test class, no need to start HTTP routes or anything.

**Comment by elmanm** [comment]
okay, that is what I thought, but in that case, how does pact get those messages? 

When I run the test above, the `handler` method should be the event message generating code, right?

**Comment by mefellows** [comment]
>  When I run the test above, the handler method should be the event message generating code, right?

Yes, pretty much:

```python
def test_verify_success():
    provider = MessageProvider(
        message_providers={
            'A document created successfully': document_created_handler,
            'A document deleted successfully': document_deleted_handler
        },
        provider='ContentProvider',
        consumer='DetectContentLambda',
        pact_dir='pacts'

    )
    with provider:
        provider.verify()
```

When the scenario `A document created successfully` runs, it invokes `document_created_handler`. The output from `document_created_handler` is compared against the expected message.

**Comment by elmanm** [comment]
> The output from document_created_handler is compared against the expected message.

This is what I had thought, but this doesn't seem to happen, walking through the code, I see nowhere that the return value is used. In my example above, I return the event as it is expected to be, but it still fails with the `nil` message. Am I doing something wrong or is this a bug in the python `MessageProvider`?

**Comment by mefellows** [comment]
The output is definitely used - see this build: https://github.com/pact-foundation/pact-python/actions/runs/3181457073/jobs/5186232842#step:7:336

I just pushed up a [change](https://github.com/pact-foundation/pact-python/compare/repro/issue-310?expand=1) in a branch to illuminate the point. 

On closer inspection, I think the issue is that the v3 serialised pact file is perhaps not being properly parsed as the Python code base uses our Ruby core, which doesn't know how to parse those matchers. What language are you using to generate the pact file? You might be able to set the serialisation to V2 to see if that helps.

Let us know how you go.

**Comment by mefellows** [comment]
If you could share a repro code base though, that would be great.

**Comment by elmanm** [comment]
The pact is generated in Java.
To change to v2, do you mean in consumer or the provider? 
I have just tried setting `version="2.0.0"` and get the same result.

Which matchers are not supported? `regex`?

I can't share the actual code because it is for an internal project, but the code above is a working example.

**Comment by mefellows** [comment]
Great! Glad you worked it all out :)
