### ISSUE TITLE
Weird issue when using Pact Verifier to verify against internal k8s service from self-hosted github action runner

### ISSUE THREAD

**Issue by alamTillit** [pact-foundation/pact-python#316]
Hi,

The issue is a bit weird and complicated. 

The situation is that we got a service that is not exposed to the public, but we would like to test it with Pact.

How I do it now is to use a self-hosted github action runner which is hosted in the same cluster and then use internal k8s dns url "http://service.namespace.svc.cluster.local:port/endpoint" to verify the endpoint in the test. The test would be triggered by pytest.

This works well when the pact test "test_pact_provider.py" is located at "$APP_HOME/pact"

However, when I placed the pact test to "$APP_HOME/tests/pact", it would start failing to access to the internal service due to 
```
"exception": {
          "class": "SocketError",
          "message": "getaddrinfo: Name or service not known"
}
```
I tried to curl the endpoint from the github runner to the internal service in k8s and it respond with 200.

Just try to figure it out why it doesn't work when the pact test is placed in a nested folder.

**Comment by YOU54F** [comment]
Hey this is going to pretty impossible to recreate or solve from our side.

If you can make a public example showing the issue we can help.

Going to close
