### ISSUE TITLE
body matches are working differently for python and .NET

### ISSUE THREAD

**Issue by IrfanSyed-PSC** [pact-foundation/pact-python#324]
Hello,

I was trying PACT in python(I have used with .NET before) and published a pact which was just verifying the type of the body.  The provider REST API object is to return a JSON Array. When the provider pact gets the response whose size is larger than the one defined in the PACT, it is failing with  the following error.  It works only if the length of the JSON is same as that of the PACT. When we use use  .will_respond_with(200, body=Like(expected)) it will just validate the type of the response body but not the length.

 Diff
       --------------------------------------
       Key: - is expected 
            + is actual 
       Matching keys and values are not shown

          ... ,
          ... ,
          ... ,
       -  Pact::UnexpectedIndex,
       +  Hash,
        ]

       Description of differences
       --------------------------------------
       * Actual array is too long and should not contain a Hash at $[4]

**Comment by mefellows** [comment]
Can you please share

1. The test code that generated this pact
2. The pact file

It looks like you don't have an array matcher, hence the exact length match

**Comment by IrfanSyed-PSC** [comment]
Here is my consumer code

`"""pact test for user service client"""

import atexit
import logging
import os
import pytest

from src.consumer import UserConsumer
from pact import Consumer,Provider,Like


log = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO)


PACT_BROKER_URL = "http://192.168.1.187:9292"


# Define where to run the mock server, for the consumer to connect to. These
# are the defaults so may be omitted
PACT_MOCK_HOST = "localhost"
PACT_MOCK_PORT = 1234

# Where to output the JSON Pact files created by any tests
PACT_DIR = os.path.dirname(os.path.realpath(__file__))


@pytest.fixture
def consumer() -> UserConsumer:
    return UserConsumer("http://{host}:{port}".format(host=PACT_MOCK_HOST, port=PACT_MOCK_PORT))


@pytest.fixture(scope="session")
def pact(request):
    """Setup a Pact Consumer, which provides the Provider mock service. This
    will generate and optionally publish Pacts to the Pact Broker"""

    version = "1.0.0"
    publish = True if version else False

    pact = Consumer("UserServiceClient", version=version).has_pact_with(
        Provider("UserService"),
        host_name=PACT_MOCK_HOST,
        port=PACT_MOCK_PORT,
        pact_dir=PACT_DIR,
        publish_to_broker=publish,
        broker_base_url=PACT_BROKER_URL
         )

    pact.start_service()

    # Make sure the Pact mocked provider is stopped when we finish, otherwise
    # port 1234 may become blocked
    atexit.register(pact.stop_service)

    yield pact

    # This will stop the Pact mock server, and if publish is True, submit Pacts
    # to the Pact Broker
    pact.stop_service()

    # Given we have cleanly stopped the service, we do not want to re-submit the
    # Pacts to the Pact Broker again atexit, since the Broker may no longer be
    # available if it has been started using the --run-broker option, as it will
    # have been torn down at that point
    pact.publish_to_broker = True


def test_get_user_non_admin(pact, consumer):
    # Define the Matcher; the expected structure and content of the response
    expected = [
  {
    "date": "2022-12-15",
    "temperatureC": 30,
    "temperatureF": 85,
    "summary": "Hot"
  },
  {
    "date": "2022-12-16",
    "temperatureC": 51,
    "temperatureF": 123,
    "summary": "Hotter"
  },
  {
    "date": "2022-12-17",
    "temperatureC": -9,
    "temperatureF": 16,
    "summary": "Cool"
  },
  {
    "date": "2022-12-18",
    "temperatureC": -7,
    "temperatureF": 20,
    "summary": "Bracing"
  }
]

    # Define the expected behaviour of the Provider. This determines how the
    # Pact mock provider will behave. In this case, we expect a body which is
    # "Like" the structure defined above. This means the mock provider will
    # return the EXACT content where defined, e.g. UserA for name, and SOME
    # appropriate content e.g. for ip_address.
    (
        pact.given("UserA exists and is not an administrator")
        .upon_receiving("a request for UserA")
        .with_request("get", "/forecast")
        .will_respond_with(200, body=Like(expected))
    )

    with pact:
        # Perform the actual request
        user = consumer.get_user()
            
        # In this case the mock Provider will have returned a valid response
        #assert user[0]['summary'] == "Chilly"

        # Make sure that all interactions defined occurred
        pact.verify()
`

**Comment by mefellows** [comment]
`Like` should be `EachLike`

**Comment by IrfanSyed-PSC** [comment]
No Luck, still the same error

**Comment by IrfanSyed-PSC** [comment]
Here is the pact file

{
  "consumer": {
    "name": "UserServiceClient"
  },
  "provider": {
    "name": "UserService"
  },
  "interactions": [
    {
      "description": "a request for UserA",
      "providerState": "UserA exists and is not an administrator",
      "request": {
        "method": "get",
        "path": "/forecast"
      },
      "response": {
        "status": 200,
        "headers": {
        },
        "body": [
          {
            "date": "2022-12-15",
            "temperatureC": 30,
            "temperatureF": 85,
            "summary": "Hot"
          },
          {
            "date": "2022-12-16",
            "temperatureC": 51,
            "temperatureF": 123,
            "summary": "Hotter"
          },
          {
            "date": "2022-12-17",
            "temperatureC": -9,
            "temperatureF": 16,
            "summary": "Cool"
          },
          {
            "date": "2022-12-18",
            "temperatureC": -7,
            "temperatureF": 20,
            "summary": "Bracing"
          }
        ],
        "matchingRules": {
          "$.body": {
            "match": "type"
          }
        }
      }
    }
  ],
  "metadata": {
    "pactSpecification": {
      "version": "2.0.0"
    }
  }
}

**Comment by mefellows** [comment]
Please see how each like is suppos.ed to work here: https://github.com/pact-foundation/pact-python#eachlikematcher-minimum1

You can't provide it an array, you must provide it a single example that becomes the template for matching on the verification side.

**Comment by IrfanSyed-PSC** [comment]
Thank you, that was the problem.
