### ISSUE TITLE
Drop support for Python < 3.7

### ISSUE THREAD

**Issue by sergeyklay** [pact-foundation/pact-python#350]
I would like to propose dropping support for Python versions below 3.7 in our project. Active development of Python 3.6 ended over 6 years ago (22 December 2016), and since then, some of libraries that we use began to drop support of older Python versions, including Python 3.6.

Main problems of supporting Python < 3.7:

- **Outdated code:** Supporting older Python versions may lead to the use of outdated and less optimal solutions.
- **Increased development and debugging time:** Supporting older Python versions requires extra effort as we need to take into account the peculiarities of each supported version.
- **Library compatibility issues:** Many modern libraries no longer support older Python versions, which may create difficulties in their usage and integration.
- **Missing new features:** Older Python versions do not support some of the new features and improvements that have been introduced in more recent versions, such as f-strings, type annotations, data classes, and others.
- **Decreased performance:** Supporting older Python versions may reduce the project's performance as some optimizations are only available in newer versions.
- **Complicated testing:** Maintaining (including tricks with CI/CD, Docker support, and local testing) across exotic Python versions requires more time and resources.

Considering the aforementioned problems, it is recommended to drop support for Python versions below 3.7, which will allow us to improve code quality, speed up development, and reduce the risk of errors arising from the use of outdated features and libraries.

/cc @mikegeeves

**Comment by YOU54F** [comment]
rationale makes total sense, we will be dropping node 14 in pact js and pact js core as they went eol last week.

we’ve just been upgrading the ruby codebases for 3.2 

checking python eol, python 3.7 drops support for in 1 month and a week 

https://endoflife.date/python

do we consider tabling that aswell, as part of this or a further motion.

i am all for supporting and advocating our users upgrading to the latest versions, i appreciate there are cases where they may not be able to, but as  our tools are open source they can maintain older versions themselves if required

**Comment by sergeyklay** [comment]
Yes, 3.7 will lose active support very soon. All I want from the resolution of this issue is to stop supporting at least 3.6. And we can get rid of 3.7 later.
