### ISSUE TITLE
verifier.verify_with_broker fails with ruby command arg ordering

### ISSUE THREAD

**Issue by CygnusAlpha** [pact-foundation/pact-python#354]
Version pact-python==1.7.0

Having failures with verifier.verify_with_broker I traced the command down to the subprocess invocation.
Which is this:
```
['/home/appuser/venv/lib/python3.10/site-packages/pact/bin/pact/bin/pact-provider-verifier', '--provider-base-url=http://localhost:1234/', '--provider=service', '--pact-broker-base-url=http://192.168.1.198:9292/', '--log-dir=/tmp', '--log-level=DEBUG', '--provider-app-version', '3', '--verbose', '--no-enable-pending']
```
Then I tried running the command manually and got these results:

this one works...
```
../venv/lib/python3.10/site-packages/pact/bin/pact/bin/pact-provider-verifier --pact-broker-base-url=http://localhost:9292/ --provider=service --provider-base-url=http://localhost:1234/
```

This one doesn't and has the args in the order that the code calls...
```
../venv/lib/python3.10/site-packages/pact/bin/pact/bin/pact-provider-verifier --provider-base-url=http://localhost:1234/ --provider=service --pact-broker-base-url=http://192.168.1.198:9292/
```

It seems that the pact-provider-verifier command needs the broker part first.

**Comment by CygnusAlpha** [comment]
Note to say that I'm still working out what's going on. I'm getting some strange results now.

**Comment by mefellows** [comment]
What's the actual error you are getting?

**Comment by CygnusAlpha** [comment]
I'm not sure I've resolved my problem, but I think now that it's not the broker url. I'm going to close this until I can get a better description.

**Comment by mefellows** [comment]
No worries, feel free to think "out loud" in the  #pact-python channel of slack.pact.io if you're not already there (i.e. create a thread and rubber duck it 🦆 )
