### ISSUE TITLE
How to disable SSL while publishing to pact broker

### ISSUE THREAD

**Issue by IrfanSyed-PSC** [pact-foundation/pact-python#355]
Hello, 

I have setup a pact broker that is running over HTTPS. In the consumer code, I want to verify the pact and publish it to pact broker but it is failing because SSL host verification is failing. Is there a way I can disable SSL host verification ?

**Comment by mefellows** [comment]
See https://github.com/pact-foundation/pact-ruby-standalone/#pact-broker-client.

You can also set `PACT_BROKER_DISABLE_SSL_VERIFICATION` to `true` (not recommended).

**Comment by IrfanSyed-PSC** [comment]
Thank you, but how can I do this python. I did set this value in python before the pytest command but it failed with the same error.

**Comment by IrfanSyed-PSC** [comment]
For now, I just set it as environment variable inside the python code and it worked

os.environ['PACT_BROKER_DISABLE_SSL_VERIFICATION'] = 'true'

**Comment by mefellows** [comment]
Yes, it needs to be an environment variable. Either set as you have above, or in the runtime / execution shell.
