### ISSUE TITLE
Migrate to `pyproject.toml`

### ISSUE THREAD

**Issue by JP-Ellis** [pact-foundation/pact-python#369]
Following [PEP 518](https://peps.python.org/pep-0518/) and [PEP 621](https://peps.python.org/pep-0621/), we should migrate the older `setup.cfg` and `setup.py` build system to one making use of `pyproject.toml`. Furthermore, the use of `setup.py` is strongly discouraged and many aspects will be discontinued:

> Setuptools offers first class support for `setup.py` files as a configuration mechanism.
>
> It is important to remember, however, that running this file as a script (e.g. `python setup.py sdist`) is strongly **discouraged**, and that the majority of the command line interfaces are (or will be) **deprecated** (e.g. `python setup.py install`, `python setup.py bdist_wininst`, …).
>
> We also recommend users to expose as much as possible configuration in a more declarative way via the [pyproject.toml](https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html) or [setup.cfg](https://setuptools.pypa.io/en/latest/userguide/declarative_config.html), and keep the `setup.py` minimal with only the dynamic parts (or even omit it completely if applicable).
>
> See [Why you shouldn’t invoke setup.py directly](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html) for more background.

<div align="right"><a href="https://setuptools.pypa.io/en/latest/userguide/quickstart.html#setuppy-discouraged">source</a></div>

The existing `setup.py` build script also makes use of [`distutils`](https://docs.python.org/3/library/distutils.html) which has been deprecated since 3.10 and is scheduled to removal in 3.12.

As part of this change, we also have an opportunity to change the underlying build system that handles the packaging of the Python package into a distributable bundle. The main ones to consider are:

- [Setuptools](https://setuptools.pypa.io/en/latest/)
- [Poetry](https://python-poetry.org/)
- [Maturin](https://github.com/PyO3/maturin)
- [Hatch](https://hatch.pypa.io/latest/)
- [PDM](https://pdm.fming.dev/latest/) and [PDM-backend](https://pdm-backend.fming.dev/)
- [Flit](https://flit.pypa.io/en/stable/index.html)

An excellent write up by Jay Qi is available in their blog post [The Basic of Python Packaging in Early 2023](https://drivendata.co/blog/python-packaging-2023).

As `pact-python` will eventually make use of the Pact Rust core, any build system considered must be able to support so-called 'extensions' (which are typically used to build C extensions).

# Deep Dive

## Setuptools

This by far the most popular build system and is the current build system being used. Extensions are supported through [`setup.py`](https://setuptools.pypa.io/en/latest/userguide/ext_modules.html).

Note that even if we keep this, closing this issue will require an extensive rework of `setup.py` due to the aforementioned deprecations.

A good example I have come across for this implementation would be following [playwright-python's `setup.py`](https://github.com/microsoft/playwright-python/blob/0e92fbc2cceba0551305f2e36f75f9b71f5d5b6e/setup.py).

## Poetry

Poetry is a very popular Python tool that predates PEP 621. Unfortunately, it does not yet support PEP 621 (though it is on the roadmap) and instead uses its own custom metadata section in `pyproject.toml`.

More concerning is the unstable support of extensions (python-poetry/poetry#2740) which effectively rules out Poetry as the build tool.

Poetry may still be useful to manage dependencies, as it does an excellent job of ensuring all dependencies installed within the virtual environment are mutually compatible. Furthermore, it integrates with [dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates#supported-repositories-and-ecosystems). This of course depends on whether the build tool can work with Poetry for dependency management.

## Maturin

Maturin is a project by the [PyO3](https://github.com/PyO3) team which maintains an ecosystem of tools that provide Rust binding for Python.

This may be an excellent option given that `pact-python` will eventually need to integrate with the Rust core and may be easier to use than Setuptools.

There is a concern that integrating too much with Rust might dissuade contributions from Python developers, and we must also check whether we can still rely on Ruby while migrating to the Rust core.

## Hatch

Hatch is build tool and front-end. It appears to have extensive support for customisations through [build hooks](https://hatch.pypa.io/latest/config/build/#build-hooks). These hooks are likely able to support both the Ruby and Rust implementations simultaneously, but this would need to be investigated properly.

## Flit

Flit is a lightweight build manager, but unfortunately does not support build extensions and therefore is not appropriate here.

## PDM

PDM describes itself as a "modern Python package and dependency manager supporting the latest PEP standards". It was created as an implementation of [PEP 582](https://peps.python.org/pep-0582/) which provides an venv-less way of managing dependencies in a similar way to npm. While PEP 582 was rejected, PDM still support this.

PDM appears to have excellent build and publishing capabilities, and the PDM backend allows for customisations through hooks [`pdm_build.py`](https://pdm-backend.fming.dev/hooks/).

**Comment by YOU54F** [comment]
I noted Ron had looked at Maturin at the first attempt of the Rust integration-  https://github.com/pact-foundation/pact-python/blob/feat/V3/pact-python-v3/pyproject.toml for an example

**Comment by JP-Ellis** [comment]
Thanks, I'll take a look. I know of `maturin` mostly from the [`ruff`](https://github.com/astral-sh/ruff) project; but have not had a need to use it before.
