### ISSUE TITLE
Add support and example for a message consumer test using Rust engine

### ISSUE THREAD

**Issue by mefellows** [pact-foundation/pact-python#380]
“Add support” means adding DSL methods that call the underlying Rust functionality.

“Add example” means create an example Python project that showcases using the functionality.

**Comment by valkolovos** [comment]
I am currently working on this

**Comment by YOU54F** [comment]
Thanks @valkolovos 

Slack thread for ref:- https://pact-foundation.slack.com/archives/C9VECUP6E/p1715370769038429
