### ISSUE TITLE
RuntimeError: The Pact mock service failed to start.

### ISSUE THREAD

**Issue by zsunshinexue** [pact-foundation/pact-python#39]
** # In the _wins7 system_. After installing pact, run the error message. Here's the information. What's the problem?**
"D:\Program Files_Work\Tool_Test\python27\python.exe" D:/co-mall/python-pact-testing-example-master/src/testuser_consumer.py
D:\Program Files_Work\Tool_Test\python27\Lib\site-packages\pact\bin\mock-service\lib\ruby\bin\..\bin.real\ruby.exe: No such file or directory -- Files_Work/Tool_Test/python27/Lib/site-packages/pact/bin/mock-service/lib/app/lib (LoadError)
Traceback (most recent call last):
  File "D:/co-mall/python-pact-testing-example-master/src/testuser_consumer.py", line 9, in <module>
    pact.start_service()
  File "D:\Program Files_Work\Tool_Test\python27\lib\site-packages\pact\pact.py", line 154, in start_service
    raise RuntimeError('The Pact mock service failed to start.')
RuntimeError: The Pact mock service failed to start.

**Comment by bethesque** [comment]
Can you tell me if `Files_Work/Tool_Test/python27/Lib/site-packages/pact/bin/mock-service/lib/app/lib` exists?

We have a problem starting the mock service on windows because windows does not implement fork, so even if you weren't getting this "file not found" error, it would blow up later on when it hit the fork. I'm working on a different method of starting the mock service that doesn't use fork, but at the moment, I'm having trouble killing the process gracefully.

**Comment by zsunshinexue** [comment]
@bethesque  This file exists，Do you mean that Pact is not supported on wins for now?

**Comment by bethesque** [comment]
You can start the mock service manually by installing the [standalone mock service](https://github.com/pact-foundation/pact-ruby-standalone/releases) which is what python uses under the hood.  You can start the mock service by running `pact-mock-service service`. This will run the process in the foreground until you quit it using ctl-c. You'll need to comment out the python code that starts and stops the mock service, and you'll need to start and stop the mock service manually each time.

If you have any expertise on sending SIGTERMs to processes on windows, please let me know [here](https://github.com/pact-foundation/pact-mock_service/issues/73)

**Comment by matthewbalvanz-wf** [comment]
@zsunshinexue In pact-python 0.8.0 I reworked how the mock service is managed. My experiments running the end-to-end tests on a Windows machine were successful, and I hope that you find a similar result with the new version.

**Comment by matthewbalvanz-wf** [comment]
@zsunshinexue I'm closing this issue as I believe we have it resolved. If that is not the case for you please re-open this, or open a new issue with details about what you are encountering.
