### ISSUE TITLE
Suggestion: rename SomethingLike to just Like

### ISSUE THREAD

**Issue by bethesque** [pact-foundation/pact-python#43]
When the SomethingLike was invented, it was a bit of a hack to help out with some brittle tests we had at REA, and I never thought it would become the standard tool it has become! In the other implementations, we're using just the name "Like" rather than "SomethingLike". It's a bit pithier. Can I suggest that you do the same for python?

**Comment by matthewbalvanz-wf** [comment]
@bethesque Yes, should be easy to do this rename. Sounds like `SomthingLike` should be added to the list of things to remove when we get to 1.0.0.
