### ISSUE TITLE
Ensure PACT_DESCRIPTION and PACT_PROVIDER_STATE env vars can be passed down to pact verify to allow selected interactions to be run

### ISSUE THREAD

**Issue by bethesque** [pact-foundation/pact-python#44]
I've removed the ruby specific output from the pact verify command (yay!)

What I would like to add is words to the effect of "to run just one interaction, please rerun the pact verify command with PACT_DESCRIPTION="..." and PACT_PROVIDER_STATE="..." environment variables set.

Can you please update to the ruby standalone version 1.4.0 and verify that the above environment variables are passed through? You should see the text `Filtering interactions by...`

**Comment by matthewbalvanz-wf** [comment]
Locally I modified the end-to-end tests to set PACT_DESCRIPTION and PACT_PROVIDER_STATE to select a single test:
```
$ make e2e
bash -c "$E2E"
[2017-09-04 16:19:14] INFO  WEBrick 1.3.1
[2017-09-04 16:19:14] INFO  ruby 2.2.2 (2015-04-13) [x86_64-darwin13]
[2017-09-04 16:19:14] INFO  WEBrick::HTTPServer#start: pid=12126 port=1234
.WARN: No content type found, performing text diff on body
.WARN: No content type found, performing text diff on body
.WARN: No content type found, performing text diff on body
....
----------------------------------------------------------------------
Ran 7 tests in 6.463s

OK

Writing pact for provider to ./pacts/consumer-provider.json
[2017-09-04 16:19:15] INFO  going to shutdown ...
[2017-09-04 16:19:15] INFO  WEBrick::HTTPServer#start done.
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
Connection to localhost port 5000 [tcp/commplex-main] succeeded!
Reading pact at ./pacts/consumer-provider.json
Filtering interactions by: {:description=>/a request for a user/, :provider_state=>/a simple json blob exists/}
WARN: Ignoring unsupported matching rules {"min"=>2} for path $['body']['results']
WARN: Only the first item will be used to match the items in the array at $['body']['results']
WARN: Ignoring unsupported matching rules {"min"=>1} for path $['body']['results'][*]['groups']

Verifying a pact between consumer and provider
  Given a simple json blob exists
    a request for a user
      with GET /users/Jonas
        returns a response which
127.0.0.1 - - [04/Sep/2017 16:19:16] "POST /_pact/provider-states/active HTTP/1.1" 200 -
127.0.0.1 - - [04/Sep/2017 16:19:16] "GET /users/Jonas HTTP/1.1" 200 -
          has status code 200
          has a matching body

1 interaction, 0 failures
```
Python subprocesses inherit their parents environment variables by default, so we should be set once we update the pact-ruby-standalone version being installed.

Will the environment variables be the official API for verifying a subset of pacts across all languages, or would it be useful in the language wrappers to have command line arguments that map to the expected environment variables? I would imagine command line options like:

```
pact-verifier --pact-description='a request for a user' --pact-provider-state='a simple json blob exists'
```
I don't have a strong opinion either way, was just weighing ease of use and discovery by users with implementation consistency in my mind.

**Comment by bethesque** [comment]
I think setting an environment variable is the most consistent way across libraries, and as it's something that we don't want people committing to their codebase, it has an appropriate level of "impermanence".

While we're here, if you can set an environment variable called `PACT_INTERACTION_RERUN_COMMAND`, which has the python command template to run a verification, the ruby pact library will spit out a list of "rerun commands", one for each failure, that will tell the user exactly what to run to execute a single interaction.

eg. the command to run a single verification in ruby is `bundle exec rake pact:verify:at[<PACT_URI>] PACT_DESCRIPTION=\"<PACT_DESCRIPTION>\" PACT_PROVIDER_STATE=\"<PACT_PROVIDER_STATE>\"`

The ruby code substitutes in the uri, description and state to create the command to run. 

This is already implemented in the ruby codebase, so it might make more sense if you just try it and see.

**Comment by matthewbalvanz-wf** [comment]
I've been experimenting with this tonight and am puzzling over how to work with the `PACT_DESCRIPTION` and `PACT_PROVIDER_STATE` environment variables. I have a branch that passes in a `PACT_INTERACTION_RERUN_COMMAND` such that the Ruby application outputs the following:

```bash
PACT_DESCRIPTION='a request for the user object of `bob`' && PACT_PROVIDER_STATE='the user `bob` exists' && /Users/matthewbalvanz/envs/pact-python362/bin/pact-verifier --provider-base-url=http://localhost:5000 --pact-urls=./pacts/consumer-provider.json --provider-states-url=http://localhost:5000/_pact/provider-states --provider-states-setup-url=http://localhost:5000/_pact/provider-states/active PACT_DESCRIPTION='a request for the user object of `bob`' PACT_PROVIDER_STATE='the user `bob` exists' # A request for the user object of `bob` given the user `bob` exists
```

But because I've been using `export` to set those variables they persist after I've run the example command. This threw me initially, as I couldn't figure out why I couldn't get all of the contracts to verify on later `pact-verifier` executions, as I had forgotten I copy/pasted this into my environment. We could add `unset` at the end of the command to undo the assignments. Does it seem like that will start making the command too long?

**Comment by bethesque** [comment]
I'm not sure why you need the `PACT_DESCRIPTION='a request for the user object of `bob`'` at the start and the end. You should only need it once. 

I'd expect this to be output:

```
PACT_DESCRIPTION='a request for the user object of `bob`' PACT_PROVIDER_STATE='the user `bob` exists' /Users/matthewbalvanz/envs/pact-python362/bin/pact-verifier --provider-base-url=http://localhost:5000 --pact-urls=./pacts/consumer-provider.json --provider-states-url=http://localhost:5000/_pact/provider-states --provider-states-setup-url=http://localhost:5000/_pact/provider-states/active 
```

I think the env vars need to be at the start of the line. I think rake does some magic that makes it work when you put them at the end of the line which is why the ruby ones can put the env vars at the end. But I could be wrong!

Just doing an experiment:

```
$ FOO=bar echo $FOO
bar

$ echo ${FOO} FOO=bar
bar FOO=bar
```

That command at least expects the env vars to be at the start.

I'd expect your invocation of the pact verifier to put the PACT_INTERACTION_RERUN_COMMAND at the start of the line too. Though... I don't know if that works for windows. When you run a shell command in ruby, there is a way to set the environment variables for the command. Perhaps there is an equivalent in python.

**Comment by matthewbalvanz-wf** [comment]
Seems I was tripping myself up by making it multiple bash commands by including `&&`. I'll get that cleaned up and see what that might look like in Windows to confirm it also works there.
