### ISSUE TITLE
Requests is pinned at 2.12.3, allow it to use a later version

### ISSUE THREAD

**Issue by bassdread** [pact-foundation/pact-python#47]
I am currently unable to build with `pact-python` as I have another library using the latest `requests` version `2.12.4` and currently `pact-python` has it pinned to `2.12.3`

Can the requirement for `requests` be changed to `requests>=2.12.3` ?

**Comment by bethesque** [comment]
Is there a version specifier in python that allows patch updates like in Ruby? It would be best practice to do "~> 2.12" (allow any increments except major ie. breaking versions) in Ruby, but I'm not sure if the norms in python.

**Comment by matthewbalvanz-wf** [comment]
@bassdread Sorry for the delay. I've been out of town and away from the computer.

As @bethesque points out, I should have made this (and the others) a range in the first place. I did some testing with requests and it looks like anything from 2.5.0 to the latest release should work properly. Would you be willing to update your PR to open it up with: `requests>=2.5.0,<3.0.0`?

**Comment by ftobia** [comment]
I'd like to suggest a different approach to relaxing version pin in `requirements.txt`. See #60. Suggestions welcome.

**Comment by richard-reece** [comment]
@matthewbalvanz-wf is there a reason to pin at all?

**Comment by richard-reece** [comment]
Similarly, six is pinned to version 1.10.0 which also causes pain :-(

**Comment by ftobia** [comment]
I was thinking that pact-python could vendor six (like, copy six.py into the pact-python codebase, to remove the dependency). It's a somewhat common pattern, and per [these docs](https://pypi.python.org/pypi/six) "[Six] is contained in only one Python file, so it can be easily copied into your project.", so it's at least supported.

If @matthewbalvanz-wf or someone else might be amenable to removing the six dependency and including six.py in the codebase, I'll put up a PR for it.

**Comment by richard-reece** [comment]
Does it need to be, though? What benefit does vendoring it bring? What issue does doing that avoid? Why can't it just be unpinned (or at least have a far more permissive version range)?

**Comment by richard-reece** [comment]
Would it be acceptable to mark the current pinned versions as minimums and then add upper limits as they arise, rather than try to predict them? The reason I say this is that a user of pact-python can always *add* a requirement to enforce their own upper limit to work around an issue, but they can't *undo* a limit that you've imposed.

**Comment by matthewbalvanz-wf** [comment]
Yep, I think that's a good next step, we can move things back if we find some time to investigate further.
