### ISSUE TITLE
Typos in documentation

### ISSUE THREAD

**Issue by hwong557** [pact-foundation/pact-python#511]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/pact-foundation/pact-python/main/CONTRIBUTING.md#issues).

### Prerequisites

- [X] I'm using the latest version of `pact-python`.
- [ ] I have read the console error message carefully (if applicable).

### Description

I found some typos, but cannot push a branch to start a PR:
```
ERROR: Permission to pact-foundation/pact-python.git denied to hwong557.
fatal: Could not read from remote repository.
```

In any case, here is a patch with the typos:
```
diff --git a/pact/consumer.py b/pact/consumer.py
index 5728123..6e0f6b5 100644
--- a/pact/consumer.py
+++ b/pact/consumer.py
@@ -13,7 +13,7 @@ class Consumer(object):
 
     >>> from pact import Consumer, Provider
     >>> consumer = Consumer('my-web-front-end')
-    >>> consumer.has_pact_with(Provider('my-backend-serivce'))
+    >>> consumer.has_pact_with(Provider('my-backend-service'))
     """
 
     def __init__(self, name, service_cls=Pact, tags=None,
@@ -79,7 +79,7 @@ class Consumer(object):
         >>> from pact import Consumer, Provider
         >>> consumer = Consumer('my-web-front-end')
         >>> consumer.has_pact_with(
-        ...   Provider('my-backend-serivce'),
+        ...   Provider('my-backend-service'),
         ...   host_name='192.168.1.1',
         ...   port=8000)
 
@@ -91,7 +91,7 @@ class Consumer(object):
             `localhost`.
         :type host_name: str
         :param port: The TCP port to use when contacting the Pact mock service.
-            This will need to tbe the same port used by your code under test
+            This will need to be the same port used by your code under test
             to contact the mock service. It defaults to: 1234
         :type port: int
         :param log_dir: The directory where logs should be written. Defaults to
```

### Steps to reproduce

Read the docs

### Expected behavior

Not have a typo.

### Actual behavior

Have a typo.

### Your environment

- Public source code:
- Is this a consumer or provider issue? Do you have information about the other side?
- Pact Python version used: `pip list | grep pact`
- Information about your Pact broker (version, hosted where, pactflow, ...)
- Operating system and version (e.g. Ubuntu 20.04.2 LTS, macOS Ventura):

### Self-service

- [ ] I'd be willing to fix this bug myself.

**Comment by mefellows** [comment]
Thanks! If you fork the repo you should still be able to open a PR, that way the change will be credited to you
