### ISSUE TITLE
Setting a custom Authentication header is not supported by current pact-verifier

### ISSUE THREAD

**Issue by jceplaras** [pact-foundation/pact-python#54]
Current [`pact-provider-verifier`](https://github.com/pact-foundation/pact-provider-verifier) supports setting a custom authentication header but `pact-verifier` does not.

**Comment by bethesque** [comment]
Thanks for the pick up. I forgot to raise an issue here when I added it.

**Comment by jceplaras** [comment]
I would also like to try and do this.

**Comment by bethesque** [comment]
The most recent standalone actually allows you to set multiple custom headers.

**Comment by jceplaras** [comment]
Should I rename this issue instead?

**Comment by bethesque** [comment]
Yes, let's turn it into the issue to do the work. I'm sure the maintainers would appreciate a PR.

**Comment by matthewbalvanz-wf** [comment]
pact-python 0.16.0 now includes pact-ruby-standalone 1.29.2. If there is anything else we need to do to support custom authentication headers let me know and I can add some options.

**Comment by bethesque** [comment]
The user needs to be able to pass in one or more `--custom-provider-header=HEADER` options to the verify script.

**Comment by matthewbalvanz-wf** [comment]
This should now be available with the inclusion of #87 in v0.17.0
