### ISSUE TITLE
Provider state teardown

### ISSUE THREAD

**Issue by ghost** [pact-foundation/pact-python#64]
Hi,

I went through the doc and tried to check the implementation but I could not find a any way to provide a  teardown callback for a particular provider state.
Is this possible right know and I am missing something or there is no such functionality yet?
Was this previously considered? If so, or not, were there any ideas that we could push forward, possibly that I could try to implement?
I could see that for pact-jvm this option is available https://github.com/DiUS/pact-jvm/issues/568.

I was thinking whether this could be done the very same way that setting provider state is being done now, just another URL that will accept the details

@edit.
Now that I think of it, most of the time teardown will be provided by the application that listens on provider-states-setup-url.
The only thing that is missing in current pact-verifier implementation is a way to tell pact-verifier that once the provider state was set and test was executed it needs to call provider-states-teardown-url (or something) with the very same consumer name and state (optionally). The underlying application would know what to do.

**Comment by bethesque** [comment]
There is no tear down in the underlying pact verifier, though the feature is available in a few pact implementations. I would recommend doing a "clean everything" at the start of the provider state setup. This approach is why the tear down is not generally needed, and hasn't (yet) been implemented.

**Comment by elliottmurray** [comment]
Resolved
