### ISSUE TITLE
Allow pacts to be stored in a specified directory

### ISSUE THREAD

**Issue by kpodl** [pact-foundation/pact-python#7]
Hi there,
First of all: Great, that you have created `pact-python`! I was just in the process of trying to resuscitate another pact implementation for Python. Yours, however, is much nicer.
Here is my feature request in story form (as you seem to prefer them that way):

As a user creating consumer contracts,
I want to be able to specify a directory in which pacts, that have been successfully verified are stored,
and I want that pact files are named "sensibly" and that name clashes are automatically resolved,
So that I do not have to use a docker volume to collect pacts.

The idea would be to allow a directory to be specified in the `has_pact_with()` method which will be passed to the `Pact` instance. Then the pact returned by the `POST` to `/pact` in `Pact.__exit__()` can be saved to a file.
If there are no objections, I would be happy to submit a pull request!

**Comment by jslvtr** [comment]
Thanks for this! May be interesting to think of them as two separate features—not that it matters much if your PR will solve for both.

> As a user creating consumer contracts, I want pact files to be named sensibly and without clashing with existing files, so that there are no errors, missing files, or overwritten files.

> As a user creating consumer contracts, I want to be able to specify which folder to save successfully verified pacts, so that I don't have to use a docker volume to collect pacts

What do you think? I'm not too experienced with this, so not sure how this would play with pact brokers, maybe @mefellows can shed some light on it

**Comment by mefellows** [comment]
The naming of the pact files is standardised and based entirely on the name of the consumer and provider. The underlying Ruby Mock Service will automatically generate the correct file name, I don't believe you can control this from Python (happy to be corrected though!).

There _is_ an edge case where if two services are named similarly, the Broker will complain - but this is very much a separate use case, and all that can really be done from the client (Python lib) is to propagate the error back to the user in a nice way.

As for the placement of the Pact files, yes, the output directly should be configurable (the Mock Service takes an argument `--pact-dir` that will save them where specified)

**Comment by matthewbalvanz-wf** [comment]
Hi @kpodl! I agree that the user experience could use some tweaks. Based on my work over in #2 I had started to move away from Docker and get the various options from the Ruby mock service implemented in the Python API, which includes `--pact-dir`. I'm hoping to get some time this week to finish it up, but my day job keeps getting in the way ;-)

My current work is over in [this branch](https://github.com/pact-foundation/pact-python/compare/manage-mock-service?expand=1) if you are interested in taking a look.

**Comment by matthewbalvanz-wf** [comment]
With #8 merged and #14 open, specifying the Pact directory should be available for creating and verifying Pacts. Feel free to re-open this if the current options don't fit your use case or if something seems missing.

https://github.com/pact-foundation/pact-python/blob/master/pact/consumer.py#L77-L79
