### ISSUE TITLE
Execution hangs with error - 'C:\Program Files (x86)\Python36-32\Lib\site-packages\pact\bin\pact\lib\ruby\bin..\bin.real\ruby.exe: No such file or directory -- Files (LoadError)'

### ISSUE THREAD

**Issue by asbhat1069** [pact-foundation/pact-python#82]
I am new to pact and am trying to run the pact tests in python , but get this error every time 'C:\Program Files (x86)\Python36-32\Lib\site-packages\pact\bin\pact\lib\ruby\bin..\bin.real\ruby.exe: No such file or directory -- Files (LoadError)' and the execution hangs there ? i see that the file exists in the path . How do i run the tests ? i run from the terminal using 'python -m unittest python-filename'

python version - 3.6.1
os - win 8

**Comment by YOU54F** [comment]
Closing due to date,  if this is still an issue with the latest version of pact python please feel free to re-raise
