### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by uv48uson** [pact-foundation/pact-python#84]
Im currently trying to get some very simple python pact examples running.  I tried a bunch of projects. But either they were to unspecific or just didnt work for me.. python pact testing example seamed to be the most simple one. So i tried it. Unfortunately im not even getting this one to run.
What it did:

downloaded the project
followed the description and did the install & execution
Im getting the folling error

```
invoke test_consumer
============================= test session starts ==============================
platform linux2 -- Python 2.7.12, pytest-3.5.0, py-1.5.3, pluggy-0.6.0
rootdir: /home/ubuntu/python-pact-testing-example, inifile:
collected 0 items / 1 errors

==================================== ERRORS ====================================
______________________ ERROR collecting test_consumer.py _______________________
test_consumer.py:11: in <module>
    pact.start_service()
/usr/local/lib/python2.7/dist-packages/pact/pact.py:161: in start_service
    self._process = Popen(command)
/usr/lib/python2.7/subprocess.py:711: in __init__
    errread, errwrite)
/usr/lib/python2.7/subprocess.py:1343: in _execute_child
    raise child_exception
E   OSError: [Errno 2] No such file or directory
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
=========================== 1 error in 0.28 seconds ============================
```
Now i have a couple of questions:

General pact paython question; project independent:
Do i have to install and run the pact mock service independently or should this be done automatically? 
Is there a detailed guideline or an simple to run example (complete) available?
I pact python mature enough? Just for simple and demostrative issues?

Project specific:
Why does the example fail?
Do i need any additional packages?

**Comment by saikirankv** [comment]
Does you code contain pact.setup() ?

**Comment by matthewbalvanz-wf** [comment]
Thanks for the question @uv48uson 

The project is definitely in a usable state, and is used to test a couple of professional projects today. 

Using the `pip install` method that [python-pact-testing-example](https://github.com/commoncode/python-pact-testing-example) outlines in the `README` should be enough to properly install pact-python. During that install process it will download a [separate package](https://github.com/pact-foundation/pact-ruby-standalone) to do the actual contract work.

There is a chance that something happened with the download of that package that caused the mock service to not get installed on your machine, but looking at the code today I think it should have blown up during install. We could certainly look at making this situation more friendly, by telling you which file is missing and that it could be an install issue.

If you are looking for an example, you might check out the [end to end](https://github.com/pact-foundation/pact-python/tree/master/e2e) tests of pact-python. These illustrate a lot of the major features of the project and [run during the build process](https://github.com/pact-foundation/pact-python/blob/master/Makefile#L32-L49).

From the gitter chat it seems you might have the environment working now. If you do happen to have the one that was broken still around, would you be able to post the results of `pip freeze`?

**Comment by uv48uson** [comment]
@saikirankv no the example code does not call pact python directly. It does call start_service

@matthewbalvanz-wf Yes. Somehow, I got it running. Locally at least. Still have an issue on my jenkins, but thats an other topic and probably related to some server settings. Unfortunatly, i dont know how exactly i fixed the problem. I think there was some weird interaction or bad setup with the two python environments 2.7 and 3.5 and their respective invoke packages. Tommorow ill post the pipenv lock here and if i (which at this moment seams very likely) can reproduce the problem tommorow, i'll do a pip freeze as well.
BTW: Thanks for ur advice on e2e, your guess on the installation issue itself. It might still help me

**Comment by briddo** [comment]
I have the same issue on MacOS 10.14.6. It just doesn't work. I will try and fix it locally and then do a pull request.

**Comment by YOU54F** [comment]
Closing due to date, there is some some additional documentation now, 

https://github.com/pact-foundation/pact-python/blob/master/CONTRIBUTING.md#running-the-tests

we are happy to accept any contributions to improve the documentation
