### ISSUE TITLE
Provide an option to ignore if there are any new get/post parameters

### ISSUE THREAD

**Issue by saikirankv** [pact-foundation/pact-python#85]
We are facing a problem like whenever a new parameter is added we end up updating the mock-apis file, its consuming lot of time, checking each and every URL where the new parameters are added. Please provide a way to by-pass if any new parameter is added.

**Comment by mefellows** [comment]
Can you please provide an example of what you mean?

**Comment by matthewbalvanz-wf** [comment]
@saikirankv I'm not sure I understand either. Pact's overall design is that if something is not specified it should not be part of any assertions, so it _should_ ignore new parameters.

Would you be able to post an example of what you are seeing?

**Comment by bethesque** [comment]
Hi @saikirankv, this is the way Pact is designed. It follows Postel's law about being strict with what you send out (so every part of the request must be "expected") and relaxed with what you accept (so the request can have extra elements that can be safely ignored). If you are finding the test maintenance too high, then perhaps you are using Pact in the wrong way. Please read this best practice guideline for using Pact https://docs.pact.io/best-practices/consumer#use-pact-for-isolated-unit-tests

**Comment by bethesque** [comment]
(Happy to discuss this further if you're having problems, but the feature you've requested will not be added)
