### ISSUE TITLE
Contributors wanted: support V3+ of the pact specification (via the pact rust core)

### ISSUE THREAD

**Issue by venthur** [pact-foundation/pact-python#88]
## The ask from the community

The `README` says you currently support V2 of the spec, please support [V3](https://github.com/pact-foundation/pact-specification/tree/version-3#version-30) as well.

## Our response

Thank you, we would <3 to see support for v3, and beyond in pact-python. It will involve migrating pact-python from the current ruby based reference implementation (the core), to a rust based reference implementaiton.

> We are severely lacking in willing participants, and we are happy to lend a hand in moving things forward <3

> If you would love to practise some python and become a pythonista, or you are a seasoned pythonista, drop into https://github.com/pact-foundation/pact-python/issues/88 and give us a shout!

## Current state of play

There has been a few attempts so far at helping tickle along progress of Pact-Python to utilise the new Rust Core.

2 on the verifier side

- https://github.com/pact-foundation/pact-python/pull/245
- https://github.com/pact-foundation/pact-python/pull/265

## Examples of python integrating with the FFI

I've put together a demonstration of Python and the Pact FFI based on some of the work done by awesome folk above.

### Pact reference

- https://github.com/pact-foundation/pact-reference/tree/master/python

### dev rel samples

These are for the consumer side, showing up to v4 Pact's being generated, and utilising the new Pact plugin framework

- https://github.com/YOU54F/pact-python-ffi

You can play with it in your browser here 

- https://killercoda.com/safdotdev/course/safacoda/grpc_plugins_quick_start_python

## The ask from you

Review the following project tracking is here

https://github.com/pact-foundation/pact-python/projects/1

Get involved!

>We would love to find new maintainers or long term contributors to the projects, so would appreciate anyone sharing the word out amongst fellow Pythonista's and see if we can bring this to the masses

## Workaround for python provider teams, being provided v3/v4 pacts

You can use the standalone verifier (based on the rust core) as an interim measure

https://docs.pact.io/implementation_guides/cli#native-binary-new

## Real Workaround for python provider teams, being provided v3/v4 pacts

- Help review the outstanding PR's
- Fork the project and propose a PR
- Let us know you want to get involved and we can run a hack day

## Edits

1. Update to provide a coherent response with actionable items at a top level

**Comment by mefellows** [comment]
You say this as if it's so easy😁

We are working on v3 but it's a lot of work.

Is there a particular feature of v3 you're particularly interested in as a priority? For example, message support (which is not a distant prospect).

**Comment by venthur** [comment]
No worries, I didn't imply it's gonna be easy. Just wanted to create the ticket, so we can keep track of the progress. I've looked into the code and wanted to start working on it, but it is unclear how it should look like in the end, especially when it comes maintaining several supported spec-versions.

So maybe we can use this issue to collect the requirements, use cases etc.

**Comment by mefellows** [comment]
No worries!

For inspiration/ideas, we can look at the [implementation guide](gist.github.com/bethesque/c858e5c15649ae525ef0cc5264b8477c) (for want of a better term) following other language implementations for guidance:

* Ruby spike (including some useful sequence diagrams): https://github.com/pact-foundation/pact-ruby-message-spike
* PHP: https://github.com/pact-foundation/pact-php/issues/29
* JS: https://github.com/pact-foundation/pact-js/tree/feat/message-pact
* Golang: https://github.com/pact-foundation/pact-go/tree/release/1.x.x

**Comment by jbw** [comment]
> You say this as if it's so easy😁
> 
> We are working on v3 but it's a lot of work.
> 
> Is there a particular feature of v3 you're particularly interested in as a priority? For example, message support (which is not a distant prospect).

Message support gets a +1 from me. Has there been any progress on this so far?

Thanks guys

**Comment by liamtmeade** [comment]
+1

**Comment by bethesque** [comment]
Someone is currently working on adding pact-message. Hop on slack.pact.io and ask around the pact-python channel.

**Comment by uglyog** [comment]
I'm going to look into this now after the initial V3 support added to Pact-JS and Pact-C++

**Comment by uglyog** [comment]
Initial prototype of V3 consumer test is in the feat/V3 branch: https://github.com/pact-foundation/pact-python/blob/feat/V3/e2e/v3/todo/tests/test_todo_consumer.py

**Comment by gdelia** [comment]
Any news on the messaging support?

**Comment by antonakospanos** [comment]
Any news here? We'd like to use Pact for our RMQ integrations too.

**Comment by elliottmurray** [comment]
So I haven't started on this and to be honest probably won't until sometime 2021 as I'm not time rich at the moment.

**Comment by bethesque** [comment]
Welcome back to having a job Elliot :P

**Comment by mefellows** [comment]
Minor update on this that's worth sharing here:

[Pact JS](https://github.com/pact-foundation/pact-js#pact-js-v3), [Pact Go](https://github.com/pact-foundation/pact-go/tree/2.x.x/) and Pact .NET (https://github.com/pact-foundation/pact-net/tree/feature/4.0.0) have all made good progress on the v3 implementation using the Rust shared core. Pact PHP is also underway.

The work in these languages has significantly improved the standard and features of the shared core, which should make integration.

If there is somebody who has a few weeks to get stuck into it, we'd be happy to do a kickoff over VC get you on the right track.

**Comment by ThatDevShparki** [comment]
Hi folks, just curious what the status of this is? My team has a vested interest in supporting some features from V3 and we are largely python developers.

@mefellows if there is any progress here / anything that I can do to help push this forward a bit?

**Comment by elliottmurray** [comment]
You can ping me on Slack and I can help with that. We starting looking at FFI bindings for this but it has stalled. I've had good intentions but been distracted. Can help out if better python devs (and more importantly those with time!) than me want to contribute.

**Comment by YOU54F** [comment]
Hey all,

There has been a few attempts so far at helping tickle along progress of Pact-Python to utilise the new Rust Core.

2 on the verifier side

- https://github.com/pact-foundation/pact-python/pull/245
- https://github.com/pact-foundation/pact-python/pull/265

I've put together a demonstration of Python and the Pact FFI based on some of the work done by awesome folk above.

These are for the consumer side, showing up to v4 Pact's being generated, and utilising the new Pact plugin framework

https://github.com/YOU54F/pact-python-ffi

We would love to find new maintainers or long term contributors to the projects, so would appreciate anyone sharing the word out amongst fellow Pythonista's and see if we can bring this to the masses

**Comment by YOU54F** [comment]
Hey @elliottmurray I am going to re-pin this, and will flesh out the top level post with the work performed to date, and it will help us as we progress in our maintainer/community chats as to the actual work required to say a language is feature complete for v3, so we know the target we are aiming towards.

As per my comment in the just closed #312 

> I think we are still in need of contributors, in order to support pact v3 and beyond, and that thread has been open for longer

We are severely lacking in willing participants, and we are happy to lend a hand in moving things forward <3

If you would love to practise some python and become a pythonista, or you are a seasoned pythonista, drop into https://github.com/pact-foundation/pact-python/issues/88 and give us a shout!

**Comment by YOU54F** [comment]
Whoops closed it by accident, fail

**Comment by YOU54F** [comment]
👋🏾 

I've been working on this on and off, and got a big push this week to really make some progress towards a user facing DSL.

If anyone wants to review, or join in please follow https://github.com/pact-foundation/pact-python/pull/367

**Comment by JP-Ellis** [comment]
I'm going to close this longstanding issue in favour of #396 which sets out a roadmap to transition towards using the Rust library.
