### ISSUE TITLE
`given`/provider state should not be necessary

### ISSUE THREAD

**Issue by bwo** [pact-foundation/pact-python#89]
Only `Pact.given()` inserts a new element into the `_interactions` array, meaning that if you don't call it for the *first* test, you'll get an exception when calling any other interaction-related methods, and if you don't call it for *subsequent* tests, you'll overwrite the previous interaction (possibly partially, leading to nonsense).

According to [the JSON schema](https://bitbucket.org/atlassian/pact-json-schema/src/8d0b9d2f38fe517dfbce0e5d0b8755eaefaacb5b/schemas/v2/schema.json?at=master&fileviewer=file-view-default#schema.json-16:30), `providerState` is an optional field, which makes sense, since not every interaction *will* require state to be set up.

As is, `pact-python` requires a bogus `given()` call for stateless interactions (and therefore requires the provider to handle that bogus state-setting).

(Less seriously, but still I think inelegantly, this also means that `given` has to be called *first*, even though the mock-English encouraged by the method names and chaining would suggest that there's no difference between "given …, upon receiving …, will respond with …" and "will respond with …, upon receiving …, given …"

**Comment by bethesque** [comment]
The given is optional in all the other impls, it should also be in python.
