### ISSUE TITLE
EachLike should allow a minimum of 0

### ISSUE THREAD

**Issue by gchorn** [pact-foundation/pact-python#92]
The `EachLike` matching helper has a keyword argument `minimum` that defaults to 1 and can not be lower than 1. However, many of our APIs return empty object arrays. Would it be possible to support a `minimum=0` setting? Or some other flag that indicates the array can be empty?

**Comment by bethesque** [comment]
Hi @gchorn. This is a common question, and here is the reason why it's not allowed https://docs.pact.io/faq#why-is-there-no-support-for-specifying-optional-attributes

**Comment by jameshalsall** [comment]
At best, this is not consistent. In PHP and Go SDKs you can specify a minimum value of 0. 

I don't personally agree that this is modelling an optional attribute. It is not modelling the presence of an attribute, it is modelling the content of an attribute. Arrays may be empty at times, and it may be fine to model that in the Pact. However, it is also important to be able to define the contract for the structure of the elements in that array when it **is** populated.

**Comment by mefellows** [comment]
Can you? You should not be able to!

**Comment by jameshalsall** [comment]
Yeah, you can :) at least this is valid for me in the Go SDK

```
eachLike(map[string]interface{}{
	"foo":  "buzz",
	"bar": 10,
}, 0)
```

**Comment by mefellows** [comment]
Thanks - but you did do _something_ valuable - you just found a bug!

**Comment by jameshalsall** [comment]
I just created a lot of work for my team because we use that 0 quirk a bit 😂

**Comment by mefellows** [comment]
Haha

If it makes you feel any better: https://github.com/pact-foundation/pact-support/pull/11
